# Generated by Django 6.0.1 on 2026-04-04 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental_period', models.CharField(choices=[('hour', 'Per Hour'), ('day', 'Per Day'), ('week', 'Per Week'), ('month', 'Per Month')], default='day', max_length=10)),
                ('minimum_rental_periods', models.PositiveIntegerField(default=1, help_text='Minimum number of periods required to rent.')),
                ('maximum_rental_periods', models.PositiveIntegerField(blank=True, help_text='Maximum number of periods allowed. Leave blank for no limit.', null=True)),
                ('deposit_required', models.BooleanField(default=False)),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Security deposit amount (if required).', max_digits=10)),
                ('available_from', models.DateField(blank=True, help_text='Start of rental availability window.', null=True)),
                ('available_until', models.DateField(blank=True, help_text='End of rental availability window.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rental_config', to='products.product')),
            ],
        ),
    ]
