# Generated by Django 6.0.1 on 2026-04-05 22:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_producttag_category_icon_category_parent_and_more'),
        ('stores', '0004_store_cached_rating_store_total_reviews_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['ordering', 'name']},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['ordering', 'created_at']},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='height',
            new_name='height_cm',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='length',
            new_name='length_cm',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='weight',
            new_name='width_cm',
        ),
        migrations.RemoveField(
            model_name='product',
            name='width',
        ),
        migrations.RemoveField(
            model_name='rentalconfig',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='rentalconfig',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category_images/'),
        ),
        migrations.AddField(
            model_name='category',
            name='ordering',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='add_to_cart_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='compare_at_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='wishlist_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productimage',
            name='alt_text',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='productimage',
            name='ordering',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productvideo',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='products/video_thumbnails/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='category_icons/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='products.category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, default='general', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_type',
            field=models.CharField(choices=[('sale', 'For Sale'), ('rent', 'For Rent')], default='sale', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, default='temp-slug', max_length=250, unique=True),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['slug'], name='products_ca_slug_da4386_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent'], name='products_ca_parent__f3c24e_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['title'], name='products_pr_title_7d8124_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['slug'], name='products_pr_slug_3edc0c_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['sku'], name='products_pr_sku_ca0cdc_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['barcode'], name='products_pr_barcode_e44f4f_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['store', 'is_active', 'is_archived'], name='products_pr_store_i_42c9c5_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'is_active'], name='products_pr_categor_50f5f1_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', 'is_archived', '-created_at'], name='products_pr_is_acti_9494ae_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_featured', 'is_active'], name='products_pr_is_feat_a1ecf6_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_boosted', 'is_active'], name='products_pr_is_boos_a8c88d_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['condition', 'sale_type'], name='products_pr_conditi_52c565_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['price'], name='products_pr_price_9b1a5f_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['latitude', 'longitude'], name='products_pr_latitud_f8957e_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['publish_at', 'is_active'], name='products_pr_publish_c75b75_idx'),
        ),
        migrations.AddIndex(
            model_name='productimage',
            index=models.Index(fields=['product', 'ordering'], name='products_pr_product_822450_idx'),
        ),
        migrations.AddIndex(
            model_name='productqa',
            index=models.Index(fields=['product', 'is_published'], name='products_pr_product_9485bc_idx'),
        ),
        migrations.AddIndex(
            model_name='producttag',
            index=models.Index(fields=['name'], name='products_pr_name_4a2b56_idx'),
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='products', to='products.producttag'),
        ),
    ]
