# Generated by Django 6.0.1 on 2026-04-06 08:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_category_options_alter_productimage_options_and_more'),
        ('stores', '0004_store_cached_rating_store_total_reviews_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalconfig',
            name='product',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_barcode_e44f4f_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_is_boos_a8c88d_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_conditi_52c565_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_latitud_f8957e_idx',
        ),
        migrations.AddField(
            model_name='product',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Which team member listed this product', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productimage',
            name='large_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='productimage',
            name='medium_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='productimage',
            name='thumbnail_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['created_by'], name='products_pr_created_f0feec_idx'),
        ),
        migrations.DeleteModel(
            name='RentalConfig',
        ),
    ]
