# Generated by Django 6.0.1 on 2026-05-09 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_image_hash_productgroup_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_quantity', models.PositiveIntegerField(help_text='Buyer must buy at least this many for this tier')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_tiers', to='products.product')),
            ],
            options={
                'ordering': ['min_quantity'],
                'indexes': [models.Index(fields=['product', 'min_quantity'], name='products_pr_product_7300ce_idx')],
                'unique_together': {('product', 'min_quantity')},
            },
        ),
    ]
