# Generated by Django 6.0.1 on 2026-05-28 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_add_search_vector'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='moderation_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='moderation_status',
            field=models.CharField(choices=[('under_review', 'Under Review'), ('published', 'Published'), ('deactivated', 'Deactivated'), ('sold_out', 'Sold Out'), ('violation', 'Violation'), ('appeal_pending', 'Appeal Under Review'), ('appeal_approved', 'Appeal Approved'), ('appeal_rejected', 'Appeal Rejected')], db_index=True, default='under_review', max_length=20),
        ),
    ]
