# Generated by Django 6.0.1 on 2026-05-30 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_category_attribute_schema_product_attributes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='free_shipping',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
