# Generated by Django 6.0.1 on 2026-07-02 14:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_product_free_shipping'),
        ('shipping', '0002_shippingtemplate_shippingmethod_and_more'),
        ('stores', '0006_storecollection'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('price__gt', 0)), name='product_price_positive'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('promo_price__isnull', True), ('promo_price__gt', 0), _connector='OR'), name='product_promo_price_positive'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('compare_at_price__isnull', True), ('compare_at_price__gt', 0), _connector='OR'), name='product_compare_at_price_positive'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('cost_price__isnull', True), ('cost_price__gte', 0), _connector='OR'), name='product_cost_price_non_negative'),
        ),
    ]
