# Generated by Django 6.0.1 on 2026-05-09 21:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OutboxEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(db_index=True, help_text='e.g. "order.placed", "payment.confirmed"', max_length=80)),
                ('payload', models.JSONField(default=dict)),
                ('dedupe_key', models.CharField(db_index=True, max_length=200, unique=True)),
                ('ref_type', models.CharField(blank=True, db_index=True, max_length=40)),
                ('ref_id', models.CharField(blank=True, db_index=True, max_length=80)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('dispatched', 'Dispatched'), ('retrying', 'Retrying'), ('dead', 'Dead (max attempts reached)')], db_index=True, default='pending', max_length=12)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=10)),
                ('next_attempt_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['next_attempt_at', 'id'],
                'indexes': [models.Index(fields=['status', 'next_attempt_at'], name='outbox_pending_due_idx')],
            },
        ),
    ]
