# Generated by Django 6.0.1 on 2026-05-16 00:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Stable identifier referenced in code, e.g. "checkout_v2".', max_length=80, unique=True)),
                ('description', models.TextField(blank=True)),
                ('kind', models.CharField(choices=[('boolean', 'Boolean (on/off)'), ('percentage', 'Percentage rollout'), ('variant', 'A/B/n variants')], max_length=12)),
                ('is_active', models.BooleanField(default=True, help_text='When False, the flag returns its default for everyone.')),
                ('rules', models.JSONField(default=dict)),
                ('default_value', models.JSONField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ExperimentExposure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag_name', models.CharField(db_index=True, max_length=80)),
                ('user_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('anon_token', models.CharField(blank=True, db_index=True, max_length=64)),
                ('variant', models.CharField(max_length=80)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'indexes': [models.Index(fields=['flag_name', 'variant', '-created_at'], name='flags_exper_flag_na_361a7a_idx')],
            },
        ),
        migrations.CreateModel(
            name='FlagOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.JSONField()),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('flag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overrides', to='flags.flag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flag_overrides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'flag'], name='flags_flago_user_id_b0e599_idx')],
                'constraints': [models.UniqueConstraint(fields=('flag', 'user'), name='uniq_flag_user_override')],
            },
        ),
    ]
