# Generated by Django 6.0.1 on 2026-06-03 08:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GatewayWebhookEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('gateway', models.CharField(choices=[('multicaixa_express', 'Multicaixa Express (Angola)'), ('stripe', 'Stripe'), ('paypal', 'PayPal'), ('manual', 'Manual / Bank transfer'), ('dev_stub', 'Dev stub (auto-succeed)')], max_length=24)),
                ('provider_event_id', models.CharField(max_length=120, unique=True)),
                ('event_type', models.CharField(db_index=True, max_length=80)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('signature_valid', models.BooleanField(default=False)),
                ('processed_ok', models.BooleanField(default=False)),
                ('error', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentIntent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gateway', models.CharField(choices=[('multicaixa_express', 'Multicaixa Express (Angola)'), ('stripe', 'Stripe'), ('paypal', 'PayPal'), ('manual', 'Manual / Bank transfer'), ('dev_stub', 'Dev stub (auto-succeed)')], max_length=24)),
                ('idempotency_key', models.CharField(max_length=80, unique=True)),
                ('purpose', models.CharField(help_text='premium_billing, checkout, dispute_refund, etc.', max_length=40)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='AOA', max_length=3)),
                ('status', models.CharField(choices=[('created', 'Created'), ('requires_action', 'Requires user action (3DS / OTP)'), ('processing', 'Processing'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded'), ('partially_refunded', 'Partially refunded')], db_index=True, default='created', max_length=24)),
                ('gateway_intent_id', models.CharField(blank=True, default='', help_text='Provider-side ID (Stripe pi_..., Multicaixa reference)', max_length=120)),
                ('client_action', models.JSONField(blank=True, default=dict, help_text='What the FE should do next: redirect URL, OTP prompt, etc.')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('failure_code', models.CharField(blank=True, default='', max_length=64)),
                ('failure_message', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_intents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GatewayTransaction',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('create', 'Create'), ('confirm', 'Confirm'), ('webhook', 'Webhook callback'), ('refund', 'Refund'), ('cancel', 'Cancel'), ('redirect', 'User redirect')], max_length=16)),
                ('gateway', models.CharField(choices=[('multicaixa_express', 'Multicaixa Express (Angola)'), ('stripe', 'Stripe'), ('paypal', 'PayPal'), ('manual', 'Manual / Bank transfer'), ('dev_stub', 'Dev stub (auto-succeed)')], max_length=24)),
                ('direction', models.CharField(choices=[('outbound', 'Outbound'), ('inbound', 'Inbound')], max_length=8)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('http_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('success', models.BooleanField(default=False)),
                ('occurred_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('intent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='payment_gateways.paymentintent')),
            ],
            options={
                'ordering': ['occurred_at'],
            },
        ),
        migrations.AddIndex(
            model_name='paymentintent',
            index=models.Index(fields=['gateway', 'status'], name='payment_gat_gateway_25c492_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentintent',
            index=models.Index(fields=['user', '-created_at'], name='payment_gat_user_id_95e316_idx'),
        ),
    ]
