# Generated by Django 6.0.1 on 2026-05-16 07:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=80)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed (all items errored)'), ('cancelled', 'Cancelled by operator')], db_index=True, default='pending', max_length=12)),
                ('total', models.PositiveIntegerField(default=0)),
                ('processed', models.PositiveIntegerField(default=0)),
                ('failed', models.PositiveIntegerField(default=0)),
                ('skipped', models.PositiveIntegerField(default=0)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulk_jobs_requested', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BulkJobItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_ref', models.CharField(db_index=True, max_length=80)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('error', 'Error'), ('skipped', 'Skipped (handler opted out)')], db_index=True, default='pending', max_length=12)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bulk_ops.bulkjob')),
            ],
        ),
        migrations.AddIndex(
            model_name='bulkjob',
            index=models.Index(fields=['status', '-created_at'], name='bulk_ops_bu_status_887d98_idx'),
        ),
        migrations.AddIndex(
            model_name='bulkjobitem',
            index=models.Index(fields=['job', 'status'], name='bulk_ops_bu_job_id_5777af_idx'),
        ),
        migrations.AddConstraint(
            model_name='bulkjobitem',
            constraint=models.UniqueConstraint(fields=('job', 'item_ref'), name='uniq_job_item_ref'),
        ),
    ]
