# Generated by Django 6.0.1 on 2026-06-16 08:52

import django.db.models.deletion
import django.db.models.expressions
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockEngineKpiSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField(unique=True)),
                ('total_active_skus', models.IntegerField(default=0)),
                ('in_stock_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('oos_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('active_reservations', models.IntegerField(default=0)),
                ('reservation_conversion_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('reservation_expiry_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('oversell_incidents', models.IntegerField(default=0)),
                ('integrity_exceptions', models.IntegerField(default=0)),
                ('flash_pools_active', models.IntegerField(default=0)),
                ('computed_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='InventorySku',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_id', models.CharField(db_index=True, max_length=64)),
                ('variant_combo_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('warehouse_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('sku_code', models.CharField(blank=True, max_length=100)),
                ('barcode', models.CharField(blank=True, max_length=50)),
                ('total_quantity', models.IntegerField(default=0)),
                ('available_quantity', models.IntegerField(default=0)),
                ('reserved_quantity', models.IntegerField(default=0)),
                ('committed_quantity', models.IntegerField(default=0)),
                ('in_transit_quantity', models.IntegerField(default=0)),
                ('damaged_quantity', models.IntegerField(default=0)),
                ('returned_quantity', models.IntegerField(default=0)),
                ('safety_stock_qty', models.IntegerField(default=0)),
                ('reorder_qty', models.IntegerField(default=0)),
                ('reorder_point', models.IntegerField(default=0)),
                ('reorder_enabled', models.BooleanField(default=True)),
                ('flash_sale_qty', models.IntegerField(default=0)),
                ('backorder_enabled', models.BooleanField(default=False)),
                ('backorder_limit', models.IntegerField(default=0)),
                ('expected_restock_date', models.DateField(blank=True, null=True)),
                ('preorder_enabled', models.BooleanField(default=False)),
                ('preorder_ship_date', models.DateField(blank=True, null=True)),
                ('count_locked', models.BooleanField(default=False)),
                ('listing_status', models.CharField(choices=[('active', 'Active'), ('out_of_stock', 'Out of stock'), ('discontinued', 'Discontinued')], db_index=True, default='active', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_skus', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FlashStockPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flash_event_id', models.CharField(db_index=True, max_length=64)),
                ('allocated_qty', models.IntegerField()),
                ('claimed_qty', models.IntegerField(default=0)),
                ('per_buyer_limit', models.PositiveSmallIntegerField(default=1)),
                ('is_open', models.BooleanField(db_index=True, default=False)),
                ('opens_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('reconciled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flash_pools', to='stock_engine.inventorysku')),
            ],
        ),
        migrations.CreateModel(
            name='BackorderDemand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(db_index=True, max_length=64)),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('allocated', 'Allocated (ready to ship)'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('allocated_at', models.DateTimeField(blank=True, null=True)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backorders', to=settings.AUTH_USER_MODEL)),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backorders', to='stock_engine.inventorysku')),
            ],
        ),
        migrations.CreateModel(
            name='RestockSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('notified', 'Notified'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=10)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restock_subs', to='stock_engine.inventorysku')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restock_subs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SkuReservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('order_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('cart_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('reservation_type', models.CharField(choices=[('cart', 'Cart (soft)'), ('checkout', 'Checkout (hard)'), ('flash_sale', 'Flash sale')], max_length=12)),
                ('status', models.CharField(choices=[('active', 'Active'), ('committed', 'Committed'), ('released', 'Released'), ('expired', 'Expired')], db_index=True, default='active', max_length=10)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, max_length=128)),
                ('extensions', models.PositiveSmallIntegerField(default=0)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='stock_engine.inventorysku')),
            ],
        ),
        migrations.CreateModel(
            name='StockEngineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(db_index=True, max_length=48)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_engine_events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StockIntegrityException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('oversell', 'Oversell (available < 0)'), ('invariant_breach', 'State sum > total'), ('event_sum_mismatch', 'Event running sum != total'), ('redis_divergence', 'Redis vs DB divergence')], db_index=True, max_length=20)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('resolved', models.BooleanField(default=False)),
                ('detected_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrity_exceptions', to='stock_engine.inventorysku')),
            ],
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('reserved', 'Reserved'), ('reservation_released', 'Released'), ('committed', 'Committed'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('returned', 'Returned'), ('returned_restocked', 'Returned restocked'), ('returned_damaged', 'Returned damaged'), ('damaged', 'Damaged'), ('written_off', 'Written off'), ('adjusted_positive', 'Adjusted +'), ('adjusted_negative', 'Adjusted -'), ('received_inbound', 'Received inbound'), ('flash_claimed', 'Flash claimed'), ('flash_released', 'Flash released')], db_index=True, max_length=24)),
                ('quantity_delta', models.IntegerField()),
                ('before_available', models.IntegerField(default=0)),
                ('after_available', models.IntegerField(default=0)),
                ('reference_type', models.CharField(blank=True, max_length=50)),
                ('reference_id', models.CharField(blank=True, max_length=64)),
                ('actor', models.CharField(default='system', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='stock_engine.inventorysku')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='FlashClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flash_claims', to=settings.AUTH_USER_MODEL)),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='stock_engine.flashstockpool')),
            ],
            options={
                'unique_together': {('pool', 'buyer')},
            },
        ),
        migrations.AddIndex(
            model_name='inventorysku',
            index=models.Index(fields=['seller', 'listing_status'], name='stock_engin_seller__77e80b_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorysku',
            index=models.Index(fields=['product_id', 'variant_combo_id'], name='stock_engin_product_d3feab_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorysku',
            index=models.Index(fields=['available_quantity'], name='stock_engin_availab_35cb63_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventorysku',
            constraint=models.CheckConstraint(condition=models.Q(('available_quantity__gte', 0), ('reserved_quantity__gte', 0), ('committed_quantity__gte', 0), ('damaged_quantity__gte', 0), ('in_transit_quantity__gte', 0), ('returned_quantity__gte', 0), ('total_quantity__gte', 0)), name='stock_qty_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='inventorysku',
            constraint=models.CheckConstraint(condition=models.Q(('total_quantity__gte', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('available_quantity'), '+', models.F('reserved_quantity')), '+', models.F('committed_quantity')), '+', models.F('damaged_quantity')), '+', models.F('in_transit_quantity')), '+', models.F('returned_quantity')))), name='stock_non_oversell_invariant'),
        ),
        migrations.AlterUniqueTogether(
            name='flashstockpool',
            unique_together={('flash_event_id', 'sku')},
        ),
        migrations.AlterUniqueTogether(
            name='restocksubscription',
            unique_together={('sku', 'user')},
        ),
        migrations.AddIndex(
            model_name='skureservation',
            index=models.Index(fields=['status', 'expires_at'], name='stock_engin_status_8edb65_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['sku', 'created_at'], name='stock_engin_sku_id_782348_idx'),
        ),
    ]
