# Generated by Django 6.0.1 on 2026-05-16 16:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('query_normalized', models.CharField(db_index=True, max_length=200)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('baseline_product_ids', models.JSONField(blank=True, default=list)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('min_notify_interval_seconds', models.PositiveIntegerField(default=86400)),
                ('last_notified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_searches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('saved_search', 'Saved search'), ('price_drop', 'Price drop'), ('back_in_stock', 'Back in stock')], db_index=True, max_length=20)),
                ('channel', models.CharField(choices=[('in_app', 'In-app notification'), ('email', 'Email'), ('push', 'Push notification'), ('outbox', 'Outbox (downstream consumers)')], max_length=10)),
                ('ref_type', models.CharField(blank=True, max_length=40)),
                ('ref_id', models.CharField(blank=True, max_length=80)),
                ('product_ids', models.JSONField(blank=True, default=list)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('delivered_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_deliveries', to=settings.AUTH_USER_MODEL)),
                ('saved_search', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='alerts.savedsearch')),
            ],
            options={
                'ordering': ['-delivered_at'],
            },
        ),
        migrations.AddIndex(
            model_name='savedsearch',
            index=models.Index(fields=['is_active', 'last_run_at'], name='alerts_save_is_acti_189c3e_idx'),
        ),
        migrations.AddIndex(
            model_name='alertdelivery',
            index=models.Index(fields=['user', '-delivered_at'], name='alerts_aler_user_id_3d34bc_idx'),
        ),
        migrations.AddIndex(
            model_name='alertdelivery',
            index=models.Index(fields=['kind', '-delivered_at'], name='alerts_aler_kind_120c0e_idx'),
        ),
        migrations.AddIndex(
            model_name='alertdelivery',
            index=models.Index(fields=['saved_search', '-delivered_at'], name='alerts_aler_saved_s_cbc86e_idx'),
        ),
    ]
