# Generated by Django 6.0.1 on 2026-04-27 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_slot',
            field=models.CharField(blank=True, choices=[('morning', 'Morning 8h-12h'), ('afternoon', 'Afternoon 12h-17h'), ('evening', 'Evening 17h-21h')], max_length=20),
        ),
    ]
