# Generated by Django 6.0.1 on 2026-04-27 15:52

import apps.payments.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_delivery_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=apps.payments.models.EncryptedCharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_phone',
            field=apps.payments.models.EncryptedCharField(blank=True, max_length=500),
        ),
    ]
