# Generated by Django 6.0.1 on 2026-04-29 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_shipping_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='fraud_action',
            field=models.CharField(default='allow', help_text='allow/flag/hold/block', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='fraud_score',
            field=models.IntegerField(default=0, help_text='0-100 fraud risk score from FraudEngine'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='fraud_action',
            field=models.CharField(default='allow', help_text='allow/flag/hold/block', max_length=20),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='fraud_score',
            field=models.IntegerField(default=0, help_text='0-100 fraud risk score from FraudEngine'),
        ),
        migrations.AddField(
            model_name='orderstatuslog',
            name='fraud_action',
            field=models.CharField(default='allow', help_text='allow/flag/hold/block', max_length=20),
        ),
        migrations.AddField(
            model_name='orderstatuslog',
            name='fraud_score',
            field=models.IntegerField(default=0, help_text='0-100 fraud risk score from FraudEngine'),
        ),
        migrations.AddField(
            model_name='payment',
            name='fraud_action',
            field=models.CharField(default='allow', help_text='allow/flag/hold/block', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='fraud_score',
            field=models.IntegerField(default=0, help_text='0-100 fraud risk score from FraudEngine'),
        ),
    ]
