# Generated by Django 6.0.1 on 2026-05-09 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_productvariantcombo'),
        ('orders', '0004_add_fraud_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='variant_combo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='inventory.productvariantcombo'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variant_options',
            field=models.JSONField(blank=True, default=dict, help_text='Snapshot of variant options at purchase time, e.g. {"Color": "Red", "Size": "M"}'),
        ),
    ]
