# Generated by Django 6.0.1 on 2026-05-09 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orderitem_variant_combo_orderitem_variant_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderTrackingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="Status code or custom (e.g. 'shipped', 'in_transit', 'out_for_delivery', 'arrived_hub')", max_length=30)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('location', models.CharField(blank=True, help_text='e.g. "Luanda - Kilamba"', max_length=120)),
                ('is_visible_to_buyer', models.BooleanField(default=True)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracking_events_created', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_events', to='orders.order')),
            ],
            options={
                'ordering': ['occurred_at'],
                'indexes': [models.Index(fields=['order', '-occurred_at'], name='orders_orde_order_i_b5c0ec_idx')],
            },
        ),
    ]
