# Generated by Django 6.0.1 on 2026-05-09 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_ordertrackingevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='platform_subsidy',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Portion of discount funded by the platform (platform-wide coupons)', max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='seller_subsidy',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Portion of discount funded by this seller (seller-specific coupons)', max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='store_credit_used',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Portion redeemed from buyer loyalty / store credit', max_digits=10),
        ),
    ]
