# Generated by Django 6.0.1 on 2026-05-09 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_platform_subsidy_order_seller_subsidy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='protection_deadline_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='protection_state',
            field=models.CharField(choices=[('none', 'None (cancelled / refunded)'), ('awaiting_seller', 'Awaiting seller confirmation'), ('awaiting_ship', 'Awaiting shipment'), ('in_transit', 'In transit'), ('in_protection', 'Buyer protection (post-delivery)'), ('completed', 'Protection completed'), ('broken', 'Protection broken (auto-refunded)')], db_index=True, default='awaiting_seller', max_length=20),
        ),
    ]
