# Generated by Django 6.0.1 on 2026-05-15 23:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_add_buyer_protection'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('wrong_item', 'Wrong item'), ('damaged', 'Damaged'), ('not_as_described', 'Not as described'), ('missing_parts', 'Missing parts'), ('changed_mind', 'Changed mind')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='return_photos/')),
                ('pickup_method', models.CharField(choices=[('pickup', 'Pickup'), ('dropoff', 'Drop-off')], default='pickup', max_length=10)),
                ('refund_destination', models.CharField(choices=[('store_credit', 'Store credit'), ('original', 'Original payment method')], default='store_credit', max_length=15)),
                ('status', models.CharField(choices=[('pending', 'Pending seller'), ('approved', 'Approved'), ('auto_approved', 'Auto-approved (seller SLA missed)'), ('rejected', 'Rejected'), ('escalated', 'Escalated to admin'), ('completed', 'Completed'), ('withdrawn', 'Withdrawn by buyer'), ('cancelled', 'Cancelled (deadline lapsed)')], db_index=True, default='pending', max_length=20)),
                ('admin_note', models.TextField(blank=True)),
                ('seller_response_deadline_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('pickup_deadline_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('escalation_deadline_at', models.DateTimeField(blank=True, null=True)),
                ('refunded_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('restocked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to='orders.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReturnEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_role', models.CharField(choices=[('buyer', 'Buyer'), ('seller', 'Seller'), ('admin', 'Admin'), ('system', 'System')], max_length=10)),
                ('from_status', models.CharField(blank=True, max_length=20)),
                ('to_status', models.CharField(max_length=20)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_events', to=settings.AUTH_USER_MODEL)),
                ('return_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='orders.returnrequest')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='returnrequest',
            index=models.Index(fields=['status', 'seller_response_deadline_at'], name='orders_retu_status_6ab5c7_idx'),
        ),
        migrations.AddIndex(
            model_name='returnrequest',
            index=models.Index(fields=['status', 'pickup_deadline_at'], name='orders_retu_status_47acd4_idx'),
        ),
        migrations.AddIndex(
            model_name='returnevent',
            index=models.Index(fields=['return_request', 'created_at'], name='orders_retu_return__66eee6_idx'),
        ),
    ]
