# Generated by Django 6.0.1 on 2026-05-20 09:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_order_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='refund',
            name='gateway_refund_id',
            field=models.CharField(blank=True, db_index=True, max_length=128),
        ),
        migrations.AddField(
            model_name='refund',
            name='last_attempt_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='refund',
            name='last_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='refund',
            name='max_attempts',
            field=models.PositiveIntegerField(default=8),
        ),
        migrations.AddField(
            model_name='refund',
            name='next_attempt_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='refund',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('processed', 'Processed'), ('rejected', 'Rejected'), ('failed', 'Failed')], default='pending', max_length=10),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['status', 'next_attempt_at'], name='orders_refu_status_86a19b_idx'),
        ),
    ]
