# Generated by Django 6.0.1 on 2026-05-30 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_order_tax_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='protection_extended',
            field=models.BooleanField(default=False),
        ),
    ]
