# Generated by Django 6.0.1 on 2026-06-20 08:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_stockreservation_idempotency_key_and_more'),
        ('orders', '0016_order_confirmed_at_order_overdue_notified_at_and_more'),
        ('products', '0013_product_free_shipping'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('total__gte', 0), ('subtotal__gte', 0), ('shipping_cost__gte', 0), ('discount__gte', 0), ('tax_amount__gte', 0)), name='ck_order_money_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0), ('unit_price__gte', 0), ('total_price__gte', 0)), name='ck_orderitem_qty_price'),
        ),
    ]
