# Generated by Django 6.0.1 on 2026-07-04 09:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_add_max_length_textfields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('message', models.CharField(blank=True, max_length=500)),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('submitted', 'Submetida'), ('countered', 'Contraproposta feita'), ('accepted', 'Aceite'), ('rejected', 'Rejeitada'), ('withdrawn', 'Retirada'), ('expired', 'Expirada')], db_index=True, default='submitted', max_length=20)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_offers', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='rentals.listing')),
                ('made_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_offers_made', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counters', to='rentals.offer')),
            ],
            options={
                'db_table': 'rental_offers',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['listing', 'status'], name='rental_offe_listing_f2cb03_idx'), models.Index(fields=['buyer', '-created_at'], name='rental_offe_buyer_i_80c833_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='rental_offer_amount_positive')],
            },
        ),
        migrations.CreateModel(
            name='Viewing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled_at', models.DateTimeField()),
                ('note', models.CharField(blank=True, max_length=300)),
                ('status', models.CharField(choices=[('requested', 'Solicitada'), ('confirmed', 'Confirmada'), ('completed', 'Realizada'), ('no_show', 'Não compareceu'), ('cancelled', 'Cancelada')], db_index=True, default='requested', max_length=20)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewings', to='rentals.listing')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_viewings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rental_viewings',
                'ordering': ['-scheduled_at'],
                'indexes': [models.Index(fields=['listing', 'status'], name='rental_view_listing_41c325_idx'), models.Index(fields=['requester', '-scheduled_at'], name='rental_view_request_2ad249_idx')],
            },
        ),
    ]
