# Generated by Django 6.0.1 on 2026-04-15 09:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerTrustScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('overall_score', models.FloatField(default=0.0, help_text='0-100 composite score')),
                ('badge_level', models.CharField(default='new', max_length=20)),
                ('badge_label', models.CharField(default='Em avaliação', max_length=50)),
                ('badge_color', models.CharField(default='#9E9E9E', max_length=10)),
                ('delivery_score', models.FloatField(default=0.0)),
                ('total_orders', models.PositiveIntegerField(default=0)),
                ('delivered_orders', models.PositiveIntegerField(default=0)),
                ('cancelled_orders', models.PositiveIntegerField(default=0)),
                ('on_time_deliveries', models.PositiveIntegerField(default=0)),
                ('avg_delivery_days', models.FloatField(blank=True, null=True)),
                ('quality_score', models.FloatField(default=0.0)),
                ('avg_rating', models.FloatField(default=0.0)),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('five_star_reviews', models.PositiveIntegerField(default=0)),
                ('one_star_reviews', models.PositiveIntegerField(default=0)),
                ('return_rate_pct', models.FloatField(default=0.0)),
                ('response_score', models.FloatField(default=0.0)),
                ('avg_confirmation_hours', models.FloatField(blank=True, null=True)),
                ('avg_chat_response_minutes', models.FloatField(blank=True, null=True)),
                ('orders_confirmed_within_24h_pct', models.FloatField(default=0.0)),
                ('verification_score', models.FloatField(default=0.0)),
                ('nif_verified', models.BooleanField(default=False)),
                ('phone_verified', models.BooleanField(default=False)),
                ('address_verified', models.BooleanField(default=False)),
                ('id_verified', models.BooleanField(default=False)),
                ('days_on_platform', models.PositiveIntegerField(default=0)),
                ('account_age_score', models.FloatField(default=0.0)),
                ('dispute_score', models.FloatField(default=100.0)),
                ('total_disputes', models.PositiveIntegerField(default=0)),
                ('disputes_resolved_in_favour_of_buyer', models.PositiveIntegerField(default=0)),
                ('unresolved_disputes', models.PositiveIntegerField(default=0)),
                ('fraud_flags', models.PositiveIntegerField(default=0)),
                ('score_30_days_ago', models.FloatField(blank=True, null=True)),
                ('score_trend', models.CharField(choices=[('up', '↑ A subir'), ('down', '↓ A descer'), ('stable', '→ Estável')], default='stable', max_length=10)),
                ('last_computed_at', models.DateTimeField(auto_now=True)),
                ('computation_version', models.CharField(default='v1', max_length=10)),
                ('score_is_public', models.BooleanField(default=False)),
                ('seller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trust_score', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'trust_seller_scores',
                'indexes': [models.Index(fields=['-overall_score'], name='trust_selle_overall_4f1ec0_idx'), models.Index(fields=['badge_level'], name='trust_selle_badge_l_f90994_idx')],
            },
        ),
        migrations.CreateModel(
            name='TrustEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=50)),
                ('event_label', models.CharField(max_length=100)),
                ('score_change', models.FloatField(default=0.0)),
                ('score_before', models.FloatField()),
                ('score_after', models.FloatField()),
                ('order_id', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trust_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'trust_events',
                'indexes': [models.Index(fields=['seller', '-created_at'], name='trust_event_seller__6557e1_idx')],
            },
        ),
        migrations.CreateModel(
            name='TrustScoreHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('badge_level', models.CharField(max_length=20)),
                ('recorded_at', models.DateField(auto_now_add=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trust_score_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'trust_score_history',
                'indexes': [models.Index(fields=['seller', '-recorded_at'], name='trust_score_seller__1d3bed_idx')],
                'unique_together': {('seller', 'recorded_at')},
            },
        ),
    ]
