# Generated by Django 6.0.1 on 2026-05-23 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_loginattempt'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='loginattempt',
            new_name='security_lo_email_a5a7f3_idx',
            old_name='security_lo_email_c2f7c5_idx',
        ),
        migrations.RenameIndex(
            model_name='loginattempt',
            new_name='security_lo_ip_f3eb65_idx',
            old_name='security_lo_ip_3e9c79_idx',
        ),
    ]
