# Generated by Django 6.0.1 on 2026-05-31 19:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0003_rename_security_lo_email_c2f7c5_idx_security_lo_email_a5a7f3_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('password_changed', 'Password changed'), ('email_changed', 'Email changed'), ('phone_changed', 'Phone changed'), ('2fa_enabled', '2FA enabled'), ('2fa_disabled', '2FA disabled'), ('login_new_device', 'Login from new device'), ('login_new_country', 'Login from new country'), ('account_suspended', 'Account suspended'), ('account_reactivated', 'Account reactivated'), ('permission_granted', 'Permission granted'), ('permission_revoked', 'Permission revoked'), ('admin_override', 'Admin override'), ('session_revoked', 'Session revoked'), ('jwt_rotation', 'JWT version bumped'), ('csp_violation', 'CSP violation reported')], db_index=True, max_length=30)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, help_text='Admin who performed the action, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action', '-created_at'], name='security_se_action_c2ff08_idx'), models.Index(fields=['user', '-created_at'], name='security_se_user_id_a067e5_idx')],
            },
        ),
        migrations.CreateModel(
            name='TrustedDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(db_index=True, max_length=64)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=2)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('alert_sent', models.BooleanField(default=False)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('label', models.CharField(blank=True, max_length=80)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='known_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_seen_at'],
                'indexes': [models.Index(fields=['user', 'last_seen_at'], name='security_tr_user_id_17717b_idx')],
                'unique_together': {('user', 'fingerprint')},
            },
        ),
    ]
