# Generated by Django 6.0.1 on 2026-04-15 19:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('not_submitted', 'Não submetido'), ('pending', 'Em análise'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado'), ('expired', 'Expirado'), ('locked', 'Bloqueado')], default='not_submitted', max_length=20)),
                ('is_active', models.BooleanField(default=False, help_text='True only when status=approved AND not expired AND monthly selfie current')),
                ('full_name', models.CharField(blank=True, max_length=200)),
                ('bi_number', models.CharField(blank=True, help_text='Angolan BI number e.g. 004567823LA042', max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('place_of_birth', models.CharField(blank=True, max_length=100)),
                ('issuing_province', models.CharField(blank=True, choices=[('Luanda', 'Luanda'), ('Benguela', 'Benguela'), ('Huambo', 'Huambo'), ('Huíla', 'Huíla'), ('Cabinda', 'Cabinda'), ('Uíge', 'Uíge'), ('Namibe', 'Namibe'), ('Malanje', 'Malanje'), ('Bié', 'Bié'), ('Moxico', 'Moxico'), ('Cunene', 'Cunene'), ('Cuando Cubango', 'Cuando Cubango'), ('Lunda Norte', 'Lunda Norte'), ('Lunda Sul', 'Lunda Sul'), ('Kwanza Norte', 'Kwanza Norte'), ('Kwanza Sul', 'Kwanza Sul'), ('Bengo', 'Bengo'), ('Zaire', 'Zaire')], max_length=50)),
                ('bi_issue_date', models.DateField(blank=True, null=True)),
                ('bi_expiry_date', models.DateField(blank=True, help_text='BI expiry date — account locks on this date', null=True)),
                ('bi_front_photo', models.ImageField(blank=True, help_text='Front side of Angolan BI', null=True, upload_to='verification/bi/front/')),
                ('bi_back_photo', models.ImageField(blank=True, help_text='Back side of Angolan BI', null=True, upload_to='verification/bi/back/')),
                ('initial_selfie', models.ImageField(blank=True, help_text='Oval-framed selfie taken during initial verification', null=True, upload_to='verification/selfies/initial/')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.CharField(blank=True, choices=[('image_unclear', 'Imagem ilegível — resubmita com melhor qualidade'), ('id_mismatch', 'Dados do BI não correspondem ao perfil'), ('id_expired', 'BI expirado — submeta BI válido'), ('fake_id', 'Documento não reconhecido como BI angolano válido'), ('selfie_mismatch', 'Selfie não corresponde à foto do BI'), ('incomplete', 'Documentos incompletos — frente e verso obrigatórios'), ('other', 'Outro motivo — ver notas do administrador')], max_length=50)),
                ('rejection_notes', models.TextField(blank=True, help_text="Admin's additional notes shown to seller")),
                ('submission_count', models.PositiveSmallIntegerField(default=0, help_text='How many times seller has submitted — track repeated rejections')),
                ('last_selfie_date', models.DateField(blank=True, help_text='Date of most recent approved monthly selfie', null=True)),
                ('next_selfie_due', models.DateField(blank=True, help_text='Date by which next selfie must be submitted', null=True)),
                ('selfie_alert_14_sent', models.BooleanField(default=False)),
                ('selfie_alert_7_sent', models.BooleanField(default=False)),
                ('bi_expiry_alert_14_sent', models.BooleanField(default=False)),
                ('bi_expiry_alert_7_sent', models.BooleanField(default=False)),
                ('first_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('lock_reason', models.CharField(blank=True, choices=[('bi_expired', 'BI expirado'), ('selfie_overdue', 'Selfie mensal em falta'), ('admin_lock', 'Bloqueado pelo administrador'), ('resubmit_pending', 'Aguarda nova submissão')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifications_reviewed', to=settings.AUTH_USER_MODEL)),
                ('seller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller_verification', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'seller_verifications',
            },
        ),
        migrations.CreateModel(
            name='MonthlySelfie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('selfie', models.ImageField(upload_to='verification/selfies/monthly/')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.CharField(blank=True, max_length=200)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selfies_reviewed', to=settings.AUTH_USER_MODEL)),
                ('verification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_selfies', to='verification_gate.sellerverification')),
            ],
            options={
                'db_table': 'seller_monthly_selfies',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='VerificationAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('details', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('verification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='verification_gate.sellerverification')),
            ],
            options={
                'db_table': 'verification_audit_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='sellerverification',
            index=models.Index(fields=['status'], name='seller_veri_status_500b7b_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerverification',
            index=models.Index(fields=['bi_expiry_date'], name='seller_veri_bi_expi_a4ad6d_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerverification',
            index=models.Index(fields=['next_selfie_due'], name='seller_veri_next_se_cfe0a6_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerverification',
            index=models.Index(fields=['is_active'], name='seller_veri_is_acti_5341ea_idx'),
        ),
    ]
