# Generated by Django 6.0.1 on 2026-05-09 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_cartitem_unique_together'),
        ('inventory', '0002_productvariantcombo'),
        ('products', '0008_product_image_hash_productgroup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='variant_combo',
            field=models.ForeignKey(blank=True, help_text='Set when product has variants and user picked one', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='inventory.productvariantcombo'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(fields=('cart', 'product', 'variant_combo'), name='cart_unique_product_variant'),
        ),
    ]
