# Generated by Django 6.0.1 on 2026-06-20 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_cart_last_abandonment_ping_at_and_more'),
        ('inventory', '0003_stockreservation_idempotency_key_and_more'),
        ('products', '0013_product_free_shipping'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='ck_cartitem_qty_positive'),
        ),
    ]
