# Generated by Django 6.0.1 on 2026-05-17 09:51

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliateProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('default_commission_rate', models.DecimalField(decimal_places=4, default=Decimal('0.0500'), help_text='0.05 = 5%', max_digits=5)),
                ('attribution_window_days', models.PositiveSmallIntegerField(default=30)),
                ('hold_period_days', models.PositiveSmallIntegerField(default=14)),
                ('min_payout_aoa', models.DecimalField(decimal_places=2, default=Decimal('5000.00'), max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AffiliateAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('tier_multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=4)),
                ('is_active', models.BooleanField(default=True)),
                ('total_earned_aoa', models.DecimalField(decimal_places=2, default=0, help_text='Sum of confirmed commissions (cached for fast reads).', max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliate_accounts', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='affiliates.affiliateprogram')),
            ],
        ),
        migrations.CreateModel(
            name='AffiliateClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_token', models.CharField(blank=True, db_index=True, max_length=64)),
                ('landing_product_id', models.CharField(blank=True, max_length=80)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=200)),
                ('referrer', models.CharField(blank=True, max_length=400)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='affiliates.affiliateaccount')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AffiliateConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(db_index=True, max_length=80)),
                ('order_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('commission_rate', models.DecimalField(decimal_places=4, max_digits=5)),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('pending', 'Pending (within hold period)'), ('confirmed', 'Confirmed (hold elapsed)'), ('paid', 'Paid out'), ('reversed', 'Reversed (refund)'), ('rejected', 'Rejected (fraud / policy)')], db_index=True, default='pending', max_length=10)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('reversed_at', models.DateTimeField(blank=True, null=True)),
                ('reversed_reason', models.CharField(blank=True, max_length=200)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('payout_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversions', to='affiliates.affiliateaccount')),
                ('click', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='affiliates.affiliateclick')),
            ],
        ),
        migrations.CreateModel(
            name='AffiliatePayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_aoa', models.DecimalField(decimal_places=2, max_digits=14)),
                ('conversion_count', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], db_index=True, default='pending', max_length=12)),
                ('external_ref', models.CharField(blank=True, max_length=80)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='affiliates.affiliateaccount')),
            ],
        ),
        migrations.AddIndex(
            model_name='affiliateclick',
            index=models.Index(fields=['account', '-created_at'], name='affiliates__account_c211c1_idx'),
        ),
        migrations.AddIndex(
            model_name='affiliateclick',
            index=models.Index(fields=['session_token', '-created_at'], name='affiliates__session_204204_idx'),
        ),
        migrations.AddIndex(
            model_name='affiliateclick',
            index=models.Index(fields=['user', '-created_at'], name='affiliates__user_id_8f6de1_idx'),
        ),
        migrations.AddIndex(
            model_name='affiliateconversion',
            index=models.Index(fields=['status', '-created_at'], name='affiliates__status_4de60c_idx'),
        ),
        migrations.AddIndex(
            model_name='affiliateconversion',
            index=models.Index(fields=['account', 'status', '-created_at'], name='affiliates__account_4216e2_idx'),
        ),
        migrations.AddConstraint(
            model_name='affiliateconversion',
            constraint=models.UniqueConstraint(fields=('account', 'order_id'), name='uniq_account_order'),
        ),
        migrations.AddConstraint(
            model_name='affiliateaccount',
            constraint=models.UniqueConstraint(fields=('user', 'program'), name='uniq_user_program'),
        ),
    ]
