# Generated by Django 6.0.1 on 2026-05-16 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('BRONZE', 'Bronze'), ('SILVER', 'Silver'), ('GOLD', 'Gold'), ('PLATINUM', 'Platinum')], max_length=10, unique=True)),
                ('rank', models.PositiveSmallIntegerField(help_text='Higher = better. Bronze=1, Platinum=4.', unique=True)),
                ('name', models.CharField(max_length=40)),
                ('spend_threshold', models.DecimalField(decimal_places=2, help_text='AOA total in qualifying window', max_digits=12)),
                ('points_multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=4)),
                ('color', models.CharField(blank=True, max_length=20)),
                ('icon', models.CharField(blank=True, max_length=40)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
        migrations.CreateModel(
            name='UserTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualifying_spend', models.DecimalField(decimal_places=2, default=0, help_text='AOA spent in last 365 days', max_digits=12)),
                ('achieved_at', models.DateTimeField(auto_now_add=True)),
                ('last_recomputed_at', models.DateTimeField(auto_now=True)),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users', to='loyalty.tier')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_tier', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PointsTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delta', models.IntegerField()),
                ('reason', models.CharField(choices=[('earn_order', 'Earned from order'), ('earn_review', 'Earned from review'), ('earn_referral', 'Earned from referral'), ('earn_birthday', 'Birthday bonus'), ('redeem_discount', 'Redeemed for discount'), ('redeem_credit', 'Redeemed for store credit'), ('adjust_admin', 'Admin adjustment'), ('expire', 'Points expired'), ('reversal', 'Reversed (refund/dispute)')], db_index=True, max_length=20)),
                ('ref_type', models.CharField(blank=True, db_index=True, max_length=40)),
                ('ref_id', models.CharField(blank=True, db_index=True, max_length=80)),
                ('balance_after', models.IntegerField()),
                ('dedupe_key', models.CharField(blank=True, db_index=True, max_length=120, null=True)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='loyalty_poi_user_id_eeff9c_idx'), models.Index(fields=['ref_type', 'ref_id'], name='loyalty_poi_ref_typ_edb62f_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'dedupe_key'), name='uniq_user_points_dedupe')],
            },
        ),
        migrations.CreateModel(
            name='TierBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('shipping_discount', 'Shipping discount %'), ('cashback_pct', 'Cashback %'), ('free_returns', 'Free returns'), ('priority_support', 'Priority support queue'), ('early_access_hours', 'Early access (h) to sales'), ('birthday_bonus', 'Birthday bonus points'), ('extended_protection', 'Extended buyer protection (days)')], max_length=24)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='loyalty.tier')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('tier', 'kind'), name='uniq_tier_benefit_kind')],
            },
        ),
    ]
