# Generated by Django 6.0.1 on 2026-05-30 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinTaskCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(choices=[('check_in', 'Daily Check-In'), ('browse_3m', 'Browse 3 minutes'), ('post_review', 'Post a review'), ('add_wishlist', 'Add to wishlist'), ('share_product', 'Share product'), ('follow_store', 'Follow store'), ('make_purchase', 'Make a purchase'), ('lucky_forest', 'Lucky Forest harvest'), ('coins_park', 'Coins Park spin'), ('merge_boss', 'MergeBoss level')], db_index=True, max_length=30)),
                ('coins_awarded', models.PositiveIntegerField(default=0)),
                ('completed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('note', models.CharField(blank=True, max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coin_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-completed_at'],
                'indexes': [models.Index(fields=['user', 'task', '-completed_at'], name='loyalty_coi_user_id_3eb0e5_idx')],
            },
        ),
        migrations.CreateModel(
            name='DailyCheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_date', models.DateField(db_index=True)),
                ('coins_awarded', models.PositiveIntegerField(default=0)),
                ('streak_day', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_ins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-check_date'],
                'indexes': [models.Index(fields=['user', '-check_date'], name='loyalty_dai_user_id_3633e2_idx')],
                'unique_together': {('user', 'check_date')},
            },
        ),
    ]
