# Generated by Django 6.0.1 on 2026-05-16 07:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Human label, e.g. "ERP integration prod".', max_length=80)),
                ('key_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('key_prefix', models.CharField(db_index=True, max_length=12)),
                ('scopes', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='NULL = never expires', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_reason', models.CharField(blank=True, max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='APIKeyUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=8)),
                ('path', models.CharField(max_length=300)),
                ('status', models.PositiveSmallIntegerField()),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=200)),
                ('error', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage', to='dev_keys.apikey')),
            ],
        ),
        migrations.AddIndex(
            model_name='apikey',
            index=models.Index(fields=['user', 'is_active'], name='dev_keys_ap_user_id_61519c_idx'),
        ),
        migrations.AddIndex(
            model_name='apikey',
            index=models.Index(fields=['key_prefix', '-created_at'], name='dev_keys_ap_key_pre_14dd17_idx'),
        ),
        migrations.AddIndex(
            model_name='apikeyusage',
            index=models.Index(fields=['key', '-created_at'], name='dev_keys_ap_key_id_177c9c_idx'),
        ),
        migrations.AddIndex(
            model_name='apikeyusage',
            index=models.Index(fields=['status', '-created_at'], name='dev_keys_ap_status_399cb0_idx'),
        ),
    ]
