# Generated by Django 6.0.1 on 2026-05-16 08:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=24, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('kind', models.CharField(choices=[('fraud', 'Fraud / risk hold'), ('counterfeit', 'Counterfeit / IP'), ('harassment', 'Harassment / abuse'), ('refund_dispute', 'Refund / dispute'), ('policy', 'Policy violation'), ('security', 'Account security'), ('other', 'Other')], db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('new', 'New (untriaged)'), ('triaged', 'Triaged'), ('investigating', 'Investigating'), ('awaiting_info', 'Awaiting info (user/seller)'), ('escalated', 'Escalated (senior admin)'), ('resolved', 'Resolved'), ('closed', 'Closed (no action)')], db_index=True, default='new', max_length=16)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], db_index=True, default='normal', max_length=8)),
                ('subject_type', models.CharField(blank=True, db_index=True, max_length=40)),
                ('subject_id', models.CharField(blank=True, db_index=True, max_length=80)),
                ('summary', models.TextField(blank=True)),
                ('resolution', models.CharField(blank=True, choices=[('no_action', 'Closed — no action needed'), ('warning_issued', 'Warning issued'), ('account_suspended', 'Account suspended'), ('account_banned', 'Account banned'), ('refund_granted', 'Refund granted'), ('product_removed', 'Product removed'), ('policy_update', 'Policy updated'), ('duplicate', 'Duplicate of another case'), ('false_positive', 'False positive')], max_length=24)),
                ('resolution_note', models.TextField(blank=True)),
                ('sla_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases_assigned', to=settings.AUTH_USER_MODEL)),
                ('opened_by_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases_admin_opened', to=settings.AUTH_USER_MODEL)),
                ('opened_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases_opened', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_role', models.CharField(choices=[('user', 'User'), ('admin', 'Admin'), ('system', 'System')], max_length=12)),
                ('event_type', models.CharField(choices=[('opened', 'Opened'), ('state_change', 'State change'), ('assigned', 'Assigned'), ('priority_change', 'Priority change'), ('link_added', 'Evidence linked'), ('link_removed', 'Evidence unlinked'), ('subject_added', 'Subject added'), ('note', 'Note'), ('resolved', 'Resolved'), ('reopened', 'Reopened')], max_length=20)),
                ('body', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='cases.case')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_type', models.CharField(choices=[('order', 'Order'), ('dispute', 'Dispute'), ('return', 'Return request'), ('fraud_assessment', 'Fraud / risk assessment'), ('product', 'Product listing'), ('payment', 'Payment'), ('chat_message', 'Chat message'), ('user_report', 'User report'), ('webhook', 'Inbound webhook event'), ('saga', 'Saga (failed compensation)')], db_index=True, max_length=24)),
                ('ref_type', models.CharField(db_index=True, max_length=40)),
                ('ref_id', models.CharField(db_index=True, max_length=80)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='cases.case')),
            ],
        ),
        migrations.CreateModel(
            name='CaseSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('reporter', 'Reporter (filed the complaint)'), ('reported', 'Reported (subject of the complaint)'), ('witness', 'Witness / additional party'), ('beneficiary', 'Beneficiary (e.g. refund recipient)')], max_length=16)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='cases.case')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_appearances', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['status', '-created_at'], name='cases_case_status_f8be30_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['assigned_to', 'status'], name='cases_case_assigne_e88b3b_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['kind', 'status'], name='cases_case_kind_76ced0_idx'),
        ),
        migrations.AddIndex(
            model_name='caseevent',
            index=models.Index(fields=['case', 'created_at'], name='cases_casee_case_id_354496_idx'),
        ),
        migrations.AddIndex(
            model_name='caseevent',
            index=models.Index(fields=['event_type', '-created_at'], name='cases_casee_event_t_1a2d09_idx'),
        ),
        migrations.AddIndex(
            model_name='caselink',
            index=models.Index(fields=['ref_type', 'ref_id'], name='cases_casel_ref_typ_33ec11_idx'),
        ),
        migrations.AddConstraint(
            model_name='caselink',
            constraint=models.UniqueConstraint(fields=('case', 'link_type', 'ref_type', 'ref_id'), name='uniq_case_link'),
        ),
        migrations.AddIndex(
            model_name='casesubject',
            index=models.Index(fields=['user', '-added_at'], name='cases_cases_user_id_9f5f80_idx'),
        ),
        migrations.AddConstraint(
            model_name='casesubject',
            constraint=models.UniqueConstraint(fields=('case', 'user', 'role'), name='uniq_case_user_role'),
        ),
    ]
