# Generated by Django 6.0.1 on 2026-05-16 00:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_add_search_vector'),
        ('search', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryProductBoost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_normalized', models.CharField(max_length=200)),
                ('score', models.FloatField(default=0.0)),
                ('sample_size', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='query_boosts', to='products.product')),
            ],
            options={
                'indexes': [models.Index(fields=['query_normalized', '-score'], name='search_quer_query_n_a05ea9_idx')],
                'constraints': [models.UniqueConstraint(fields=('query_normalized', 'product'), name='uniq_query_product_boost')],
            },
        ),
        migrations.CreateModel(
            name='SearchEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_normalized', models.CharField(db_index=True, max_length=200)),
                ('kind', models.CharField(choices=[('impression', 'Impression (shown in results)'), ('click', 'Clicked through to detail'), ('cart', 'Added to cart from search'), ('purchase', 'Purchased after searching')], db_index=True, max_length=12)),
                ('position', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('anon_token', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_events', to='products.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['query_normalized', 'kind', '-created_at'], name='search_sear_query_n_7c33ba_idx'), models.Index(fields=['product', 'kind', '-created_at'], name='search_sear_product_71b3e1_idx')],
            },
        ),
    ]
