# Generated by Django 6.0.1 on 2026-05-24 20:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_rights', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CookieConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_key', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('analytics', models.BooleanField(default=False)),
                ('marketing', models.BooleanField(default=False)),
                ('preferences', models.BooleanField(default=False)),
                ('ip_hash', models.CharField(blank=True, default='', max_length=64)),
                ('user_agent', models.CharField(blank=True, default='', max_length=200)),
                ('policy_version', models.CharField(blank=True, default='v1', max_length=20)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cookie_consents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'data_rights_cookie_consent',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='data_rights_user_id_50a396_idx'), models.Index(fields=['consent_key', '-created_at'], name='data_rights_consent_b8db55_idx')],
            },
        ),
    ]
