# Generated by Django 6.0.1 on 2026-04-05 22:24

import apps.payments.models
import apps.verification.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0002_sellerverification_rejection_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='sellerverification',
            old_name='user',
            new_name='seller',
        ),
        migrations.RemoveField(
            model_name='sellerverification',
            name='last_selfie_update',
        ),
        migrations.AddField(
            model_name='sellerverification',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sellerverification',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sellerverification',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sellerverification',
            name='id_document',
            field=models.ImageField(upload_to='verification/documents/'),
        ),
        migrations.AlterField(
            model_name='sellerverification',
            name='id_number',
            field=apps.payments.models.EncryptedCharField(help_text='Angolan BI number — stored encrypted', max_length=500, validators=[apps.verification.models.validate_angolan_bi]),
        ),
        migrations.AlterField(
            model_name='sellerverification',
            name='rejection_reason',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sellerverification',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=15),
        ),
        migrations.AlterField(
            model_name='verificationlog',
            name='note',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='verificationlog',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='sellerverification',
            index=models.Index(fields=['seller', 'status'], name='verificatio_seller__824447_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerverification',
            index=models.Index(fields=['status', '-created_at'], name='verificatio_status_8f2186_idx'),
        ),
    ]
