# Generated by Django 6.0.1 on 2026-05-29 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0003_rename_user_sellerverification_seller_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerverification',
            name='bank_proof',
            field=models.FileField(blank=True, null=True, upload_to='verification/bank_proof/'),
        ),
        migrations.AddField(
            model_name='sellerverification',
            name='business_licence',
            field=models.FileField(blank=True, null=True, upload_to='verification/business_licence/'),
        ),
        migrations.AddField(
            model_name='sellerverification',
            name='id_document_back',
            field=models.ImageField(blank=True, null=True, upload_to='verification/documents/'),
        ),
        migrations.AddField(
            model_name='sellerverification',
            name='is_business_account',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sellerverification',
            name='power_of_attorney',
            field=models.FileField(blank=True, null=True, upload_to='verification/poa/'),
        ),
    ]
