# Generated by Django 6.0.1 on 2026-05-17 20:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0002_productvariantcombo'),
        ('products', '0010_add_search_vector'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WaitlistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('waiting', 'Waiting for restock'), ('notified', 'Notified — buyer should act'), ('converted', 'Converted — buyer purchased'), ('cancelled', 'Cancelled by buyer'), ('expired', 'Expired (stale entry purged)')], db_index=True, default='waiting', max_length=10)),
                ('position', models.PositiveIntegerField(db_index=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('converted_order_id', models.CharField(blank=True, max_length=80)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to=settings.AUTH_USER_MODEL)),
                ('variant_combo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to='inventory.productvariantcombo')),
            ],
            options={
                'ordering': ['product', 'position'],
                'indexes': [models.Index(fields=['product', 'status', 'position'], name='waitlist_wa_product_43bda6_idx'), models.Index(fields=['user', '-joined_at'], name='waitlist_wa_user_id_0bc21c_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'waiting')), fields=('user', 'product', 'variant_combo'), name='uniq_active_waitlist_entry')],
            },
        ),
    ]
