# Generated by Django 6.0.1 on 2026-05-16 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0010_add_search_vector'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyDemand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(db_index=True)),
                ('units', models.PositiveIntegerField(default=0)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_demand', to='products.product')),
            ],
            options={
                'ordering': ['-day'],
                'indexes': [models.Index(fields=['product', '-day'], name='forecasting_product_a6dddc_idx'), models.Index(fields=['day'], name='forecasting_day_1bc9d4_idx')],
                'constraints': [models.UniqueConstraint(fields=('product', 'day'), name='uniq_product_day')],
            },
        ),
        migrations.CreateModel(
            name='DemandForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horizon_days', models.PositiveSmallIntegerField(default=30)),
                ('predicted_units', models.DecimalField(decimal_places=2, max_digits=12)),
                ('lower_bound', models.DecimalField(decimal_places=2, max_digits=12)),
                ('upper_bound', models.DecimalField(decimal_places=2, max_digits=12)),
                ('daily_mean', models.DecimalField(decimal_places=4, max_digits=10)),
                ('daily_stddev', models.DecimalField(decimal_places=4, max_digits=10)),
                ('method', models.CharField(choices=[('ewma', 'Exponentially weighted moving avg (with weekday seasonality)'), ('sma', 'Simple moving average'), ('zero', 'Zero (insufficient history)')], max_length=8)),
                ('sample_size', models.PositiveIntegerField(help_text='Days of history that fed this forecast')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demand_forecasts', to='products.product')),
            ],
            options={
                'indexes': [models.Index(fields=['product', '-generated_at'], name='forecasting_product_076acf_idx')],
                'constraints': [models.UniqueConstraint(fields=('product', 'horizon_days'), name='uniq_product_horizon')],
            },
        ),
        migrations.CreateModel(
            name='ReorderRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_stock', models.PositiveIntegerField()),
                ('reorder_point', models.PositiveIntegerField()),
                ('recommended_qty', models.PositiveIntegerField()),
                ('safety_stock', models.PositiveIntegerField()),
                ('lead_time_days', models.PositiveSmallIntegerField(default=7)),
                ('forecast_daily_mean', models.DecimalField(decimal_places=4, max_digits=10)),
                ('forecast_daily_stddev', models.DecimalField(decimal_places=4, max_digits=10)),
                ('reason', models.CharField(max_length=300)),
                ('action', models.CharField(choices=[('pending', 'Pending seller action'), ('ordered', 'Seller marked as ordered'), ('dismissed', 'Seller dismissed'), ('expired', 'Expired (replaced by newer recommendation)')], db_index=True, default='pending', max_length=10)),
                ('action_at', models.DateTimeField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reorder_recommendations', to='products.product')),
            ],
            options={
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['product', '-generated_at'], name='forecasting_product_a9d84f_idx'), models.Index(fields=['action', '-generated_at'], name='forecasting_action_396046_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('action', 'pending')), fields=('product',), name='uniq_pending_recommendation_per_product')],
            },
        ),
    ]
