# Generated by Django 6.0.1 on 2026-05-23 22:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contentflag',
            name='resolution_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='contentflag',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contentflag',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_flags_resolved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contentflag',
            name='severity',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='contentflag',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('escalated', 'Escalated')], db_index=True, default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='contentflag',
            name='target_user',
            field=models.ForeignKey(blank=True, help_text='Owner of the flagged content. Used by escalation engine.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_flags_against', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='contentflag',
            index=models.Index(fields=['status', '-created_at'], name='moderation__status_3967bb_idx'),
        ),
        migrations.AddIndex(
            model_name='contentflag',
            index=models.Index(fields=['target_user', 'status'], name='moderation__target__c34ad3_idx'),
        ),
    ]
