# Generated by Django 6.0.1 on 2026-05-25 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0002_contentflag_queue_state'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProtectedBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=120, unique=True)),
                ('variants', models.JSONField(blank=True, default=list)),
                ('owner_email', models.EmailField(blank=True, default='', max_length=254)),
                ('policy', models.CharField(choices=[('review', 'Route to brand-review queue'), ('block', 'Hard-refuse listing creation'), ('manual', 'No automatic action — manual review only')], default='review', max_length=10)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'moderation_protected_brand',
                'ordering': ['name'],
            },
        ),
    ]
