# Generated by Django 6.0.1 on 2026-06-14 12:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CapitalisedDevelopment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_name', models.CharField(max_length=160)),
                ('capitalised_cents', models.BigIntegerField(default=0)),
                ('amortised_cents', models.BigIntegerField(default=0)),
                ('useful_life_months', models.PositiveSmallIntegerField(default=36)),
                ('status', models.CharField(choices=[('capitalising', 'Capitalising'), ('live', 'Live (amortising)'), ('impaired', 'Impaired'), ('fully_amortised', 'Fully amortised')], default='capitalising', max_length=16)),
                ('went_live_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialStatementSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=7, unique=True)),
                ('total_revenue_cents', models.BigIntegerField(default=0)),
                ('total_cor_cents', models.BigIntegerField(default=0)),
                ('gross_profit_cents', models.BigIntegerField(default=0)),
                ('total_opex_cents', models.BigIntegerField(default=0)),
                ('ebitda_cents', models.BigIntegerField(default=0)),
                ('other_income_cents', models.BigIntegerField(default=0)),
                ('pbt_cents', models.BigIntegerField(default=0)),
                ('income_tax_cents', models.BigIntegerField(default=0)),
                ('net_profit_cents', models.BigIntegerField(default=0)),
                ('total_assets_cents', models.BigIntegerField(default=0)),
                ('total_liabilities_cents', models.BigIntegerField(default=0)),
                ('total_equity_cents', models.BigIntegerField(default=0)),
                ('balance_sheet_balanced', models.BooleanField(default=True)),
                ('trial_balance_balanced', models.BooleanField(default=True)),
                ('take_rate_pct', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('gross_margin_pct', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('computed_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GLAccount',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('account_type', models.CharField(choices=[('asset', 'Asset'), ('liability', 'Liability'), ('equity', 'Equity'), ('revenue', 'Revenue'), ('cost_of_revenue', 'Cost of revenue'), ('operating_expense', 'Operating expense'), ('other', 'Other income/expense')], max_length=20)),
                ('normal_balance', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], max_length=6)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='AccountingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(db_index=True, max_length=48)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounting_events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AccountingPeriod',
            fields=[
                ('period', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('is_locked', models.BooleanField(db_index=True, default=False)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('unlocked_reason', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-period'],
            },
        ),
        migrations.CreateModel(
            name='AccountReceivable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('seller_chargeback', 'Seller chargeback recovery'), ('courier_shortfall', 'Courier cash shortfall'), ('partner_fee', 'Partner fee'), ('insurance_claim', 'Insurance claim')], max_length=20)),
                ('amount_cents', models.BigIntegerField()),
                ('recovered_cents', models.BigIntegerField(default=0)),
                ('account_code', models.CharField(default='1100', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('partially_recovered', 'Partially recovered'), ('recovered', 'Recovered'), ('written_off', 'Written off')], db_index=True, default='open', max_length=20)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('raised_at', models.DateField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('debtor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receivables', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeferredRevenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('annual_fee', 'Annual fee'), ('ad_credits', 'Ad credits')], max_length=12)),
                ('total_cents', models.BigIntegerField()),
                ('recognised_cents', models.BigIntegerField(default=0)),
                ('months_total', models.PositiveSmallIntegerField(default=12)),
                ('months_recognised', models.PositiveSmallIntegerField(default=0)),
                ('revenue_account_code', models.CharField(default='4010', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('started_at', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deferred_revenue', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EscrowLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('gross_amount_cents', models.BigIntegerField()),
                ('commission_cents', models.BigIntegerField(default=0)),
                ('net_seller_cents', models.BigIntegerField(default=0)),
                ('refunded_cents', models.BigIntegerField(default=0)),
                ('status', models.CharField(choices=[('held', 'Held'), ('releasable', 'Releasable'), ('released', 'Released'), ('clawed_back', 'Clawed back'), ('partially_clawed', 'Partially clawed')], db_index=True, default='held', max_length=18)),
                ('payment_method', models.CharField(blank=True, max_length=16)),
                ('release_trigger', models.CharField(blank=True, max_length=20)),
                ('funds_received_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escrow_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_date', models.DateField(db_index=True)),
                ('period', models.CharField(db_index=True, max_length=7)),
                ('description', models.CharField(max_length=300)),
                ('source_type', models.CharField(choices=[('system_auto', 'System auto'), ('manual', 'Manual'), ('reversal', 'Reversal'), ('correction', 'Correction'), ('accrual', 'Accrual'), ('payroll', 'Payroll')], db_index=True, default='system_auto', max_length=16)),
                ('source_id', models.CharField(blank=True, db_index=True, max_length=80)),
                ('is_auto', models.BooleanField(default=True)),
                ('is_reversal', models.BooleanField(default=False)),
                ('total_cents', models.BigIntegerField(default=0)),
                ('posted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries', to=settings.AUTH_USER_MODEL)),
                ('reversed_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversals', to='accounting.journalentry')),
            ],
            options={
                'ordering': ['-posted_at'],
            },
        ),
        migrations.CreateModel(
            name='FxRevaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField()),
                ('currency', models.CharField(max_length=3)),
                ('foreign_amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('opening_rate', models.DecimalField(decimal_places=4, max_digits=12)),
                ('closing_rate', models.DecimalField(decimal_places=4, max_digits=12)),
                ('gain_loss_cents', models.BigIntegerField(default=0)),
                ('rate_source', models.CharField(default='BNA', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounting.journalentry')),
            ],
        ),
        migrations.CreateModel(
            name='DisputeReserveLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField(unique=True)),
                ('open_dispute_value_cents', models.BigIntegerField(default=0)),
                ('expected_loss_cents', models.BigIntegerField(default=0)),
                ('prior_reserve_cents', models.BigIntegerField(default=0)),
                ('adjustment_cents', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounting.journalentry')),
            ],
        ),
        migrations.CreateModel(
            name='JournalLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit_cents', models.BigIntegerField(default=0)),
                ('credit_cents', models.BigIntegerField(default=0)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('currency', models.CharField(default='AOA', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='accounting.glaccount')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='accounting.journalentry')),
                ('party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ManualEntryApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
                ('period', models.CharField(max_length=7)),
                ('entry_date', models.DateField()),
                ('lines', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('posted', 'Posted')], db_index=True, default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('posted_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounting.journalentry')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manual_entries_requested', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SellerPayableLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(db_index=True, max_length=64)),
                ('gross_cents', models.BigIntegerField()),
                ('commission_cents', models.BigIntegerField()),
                ('net_cents', models.BigIntegerField()),
                ('adjustments_cents', models.BigIntegerField(default=0)),
                ('payout_batch_id', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('accrued', 'Accrued'), ('adjusting', 'Adjusting'), ('paid', 'Paid'), ('disputed', 'Disputed')], db_index=True, default='accrued', max_length=10)),
                ('accrued_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payable_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubLedgerReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recon_date', models.DateField(db_index=True)),
                ('ledger', models.CharField(choices=[('escrow', 'Escrow (2000)'), ('wallet', 'Wallet (2010)'), ('seller_payable', 'Seller payable (2020)'), ('cod_clearing', 'COD clearing (2060)')], max_length=16)),
                ('gl_account_code', models.CharField(max_length=10)),
                ('sub_ledger_total_cents', models.BigIntegerField(default=0)),
                ('gl_balance_cents', models.BigIntegerField(default=0)),
                ('difference_cents', models.BigIntegerField(default=0)),
                ('balanced', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('recon_date', 'ledger')},
            },
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['period', 'entry_date'], name='accounting__period_3deaf9_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['source_type', 'source_id'], name='accounting__source__3d844c_idx'),
        ),
        migrations.AddIndex(
            model_name='journalline',
            index=models.Index(fields=['account', '-created_at'], name='accounting__account_db99a5_idx'),
        ),
        migrations.AddConstraint(
            model_name='journalline',
            constraint=models.CheckConstraint(condition=models.Q(('debit_cents__gte', 0), ('credit_cents__gte', 0), models.Q(('credit_cents', 0), ('debit_cents', 0), _negated=True), models.Q(('debit_cents', 0), ('credit_cents', 0), _connector='OR')), name='accounting_line_exactly_one_direction'),
        ),
        migrations.AddIndex(
            model_name='sellerpayableledger',
            index=models.Index(fields=['seller', 'status'], name='accounting__seller__e8a08c_idx'),
        ),
    ]
