// Mock data — replace with API calls when backend products are ready

export const CATEGORIES = [
  { id: 'all',       label: 'Tudo',        icon: '◈' },
  { id: 'fashion',   label: 'Moda',        icon: '👗' },
  { id: 'tech',      label: 'Tecnologia',  icon: '📱' },
  { id: 'home',      label: 'Casa',        icon: '🏠' },
  { id: 'beauty',    label: 'Beleza',      icon: '✨' },
  { id: 'food',      label: 'Alimentação', icon: '🛒' },
  { id: 'sport',     label: 'Desporto',    icon: '⚽' },
  { id: 'kids',      label: 'Crianças',    icon: '🧸' },
]

export const MOCK_PRODUCTS = [
  {
    id: '1',
    name: 'Vestido Capulana Premium',
    price: 8500,
    original_price: 12000,
    currency: 'AOA',
    category: 'fashion',
    seller: 'Moda Luanda',
    seller_verified: true,
    rating: 4.8,
    reviews: 124,
    sold: 342,
    express: true,
    image_color: '#8B4513',
    badge: 'Mais Vendido',
    badge_color: '#C9A84C',
  },
  {
    id: '2',
    name: 'Smartphone Samsung A55',
    price: 185000,
    original_price: 210000,
    currency: 'AOA',
    category: 'tech',
    seller: 'TechShop Angola',
    seller_verified: true,
    rating: 4.6,
    reviews: 89,
    sold: 156,
    express: true,
    image_color: '#1a1a2e',
    badge: 'Express',
    badge_color: '#C9A84C',
  },
  {
    id: '3',
    name: 'Conjunto de Panelas Antiaderentes',
    price: 32000,
    original_price: 45000,
    currency: 'AOA',
    category: 'home',
    seller: 'Casa & Lar',
    seller_verified: false,
    rating: 4.3,
    reviews: 56,
    sold: 98,
    express: false,
    image_color: '#2d4a22',
    badge: '-29%',
    badge_color: '#dc2626',
  },
  {
    id: '4',
    name: 'Perfume Africain Gold 100ml',
    price: 15000,
    original_price: null,
    currency: 'AOA',
    category: 'beauty',
    seller: 'Beauty Angola',
    seller_verified: true,
    rating: 4.9,
    reviews: 203,
    sold: 521,
    express: true,
    image_color: '#4a3728',
    badge: 'Novo',
    badge_color: '#059669',
  },
  {
    id: '5',
    name: 'Ténis Nike Air Max',
    price: 52000,
    original_price: 68000,
    currency: 'AOA',
    category: 'sport',
    seller: 'SportZone AO',
    seller_verified: true,
    rating: 4.7,
    reviews: 177,
    sold: 289,
    express: true,
    image_color: '#1e3a5f',
    badge: 'Express',
    badge_color: '#C9A84C',
  },
  {
    id: '6',
    name: 'Bolsa de Couro Genuíno',
    price: 28000,
    original_price: 35000,
    currency: 'AOA',
    category: 'fashion',
    seller: 'Moda Luanda',
    seller_verified: true,
    rating: 4.5,
    reviews: 67,
    sold: 134,
    express: false,
    image_color: '#5c3d2e',
    badge: '-20%',
    badge_color: '#dc2626',
  },
  {
    id: '7',
    name: 'Auriculares Bluetooth Pro',
    price: 22000,
    original_price: 28000,
    currency: 'AOA',
    category: 'tech',
    seller: 'TechShop Angola',
    seller_verified: true,
    rating: 4.4,
    reviews: 92,
    sold: 201,
    express: true,
    image_color: '#111827',
    badge: 'Express',
    badge_color: '#C9A84C',
  },
  {
    id: '8',
    name: 'Kit Skincare Natural',
    price: 18500,
    original_price: null,
    currency: 'AOA',
    category: 'beauty',
    seller: 'Beauty Angola',
    seller_verified: true,
    rating: 4.8,
    reviews: 145,
    sold: 388,
    express: true,
    image_color: '#d4a373',
    badge: 'Mais Vendido',
    badge_color: '#C9A84C',
  },
]

export const BANNERS = [
  {
    id: '1',
    title: 'Entrega Express\nem Luanda',
    subtitle: 'Receba hoje mesmo',
    bg: 'linear-gradient(135deg, #C9A84C 0%, #A67C35 100%)',
    textColor: '#0A0A0A',
  },
  {
    id: '2',
    title: 'Moda Angolana\nPremium',
    subtitle: 'Capulanas e muito mais',
    bg: 'linear-gradient(135deg, #1a1a2e 0%, #16213e 100%)',
    textColor: '#C9A84C',
  },
  {
    id: '3',
    title: 'Tech ao Melhor\nPreço',
    subtitle: 'Smartphones e acessórios',
    bg: 'linear-gradient(135deg, #0f2027 0%, #203a43 100%)',
    textColor: '#FFFFFF',
  },
]

export const formatPrice = (price) => {
  return new Intl.NumberFormat('pt-AO', {
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  }).format(price) + ' Kz'
}
