# Generated by Django 6.0.1 on 2026-06-03 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer_engagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(db_index=True, max_length=64)),
                ('kind', models.CharField(choices=[('push', 'Push notification'), ('email', 'Email'), ('inapp', 'In-app banner')], default='email', max_length=8)),
                ('locale', models.CharField(default='pt-AO', max_length=10)),
                ('subject', models.CharField(blank=True, default='', max_length=255)),
                ('body', models.TextField()),
                ('deep_link', models.CharField(blank=True, default='', max_length=255)),
                ('cta_label', models.CharField(blank=True, default='', max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['key', 'kind', 'locale'],
                'unique_together': {('key', 'kind', 'locale')},
            },
        ),
    ]
