# Generated by Django 6.0.1 on 2026-05-23 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0002_couponredemption'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='couponredemption',
            new_name='promotions__user_id_445fe8_idx',
            old_name='promotions__user_id_coup_idx',
        ),
        migrations.RenameIndex(
            model_name='couponredemption',
            new_name='promotions__status_f2f543_idx',
            old_name='promotions__status__app_idx',
        ),
    ]
