# Generated by Django 6.0.1 on 2026-05-29 22:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_category_attribute_schema_product_attributes_and_more'),
        ('promotions', '0003_rename_promotions__user_id_coup_idx_promotions__user_id_445fe8_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku_id', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('is_notified', models.BooleanField(db_index=True, default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_notifications', to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'product', 'sku_id')},
            },
        ),
        migrations.CreateModel(
            name='UserCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('available', 'Available'), ('used', 'Used'), ('expired', 'Expired')], db_index=True, default='available', max_length=12)),
                ('collected_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('order_id', models.CharField(blank=True, max_length=80)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collected_by', to='promotions.coupon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collected_coupons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-collected_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='promotions__user_id_a1d1f0_idx')],
                'unique_together': {('user', 'coupon')},
            },
        ),
    ]
