# Generated by Django 6.0.1 on 2026-05-30 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0004_stocknotification_usercoupon'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('kind', models.CharField(choices=[('platform', 'Platform-wide'), ('category', 'Category'), ('seller', 'Seller')], default='platform', max_length=12)),
                ('headline', models.CharField(blank=True, max_length=200)),
                ('subheading', models.CharField(blank=True, max_length=400)),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='sale_events/')),
                ('bg_color', models.CharField(default='#C9A84C', max_length=20)),
                ('starts_at', models.DateTimeField(db_index=True)),
                ('ends_at', models.DateTimeField(db_index=True)),
                ('is_active', models.BooleanField(default=True)),
                ('cta_label', models.CharField(default='Ver ofertas', max_length=40)),
                ('cta_url', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-starts_at'],
                'indexes': [models.Index(fields=['is_active', 'starts_at', 'ends_at'], name='promotions__is_acti_44a0f8_idx')],
            },
        ),
    ]
