# Generated by Django 6.0.1 on 2026-04-05 22:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_category_options_alter_productimage_options_and_more'),
        ('recommendations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinteraction',
            name='type',
            field=models.CharField(choices=[('view', 'View'), ('wishlist', 'Wishlist'), ('cart', 'Cart'), ('purchase', 'Purchase'), ('review', 'Review'), ('share', 'Share')], max_length=10),
        ),
        migrations.AddIndex(
            model_name='backinstockalert',
            index=models.Index(fields=['notified', 'product'], name='recommendat_notifie_0a0a0f_idx'),
        ),
        migrations.AddIndex(
            model_name='browsingsession',
            index=models.Index(fields=['user', '-last_active'], name='recommendat_user_id_badfdb_idx'),
        ),
        migrations.AddIndex(
            model_name='pricealert',
            index=models.Index(fields=['is_triggered', 'product'], name='recommendat_is_trig_2cc678_idx'),
        ),
        migrations.AddIndex(
            model_name='productinteraction',
            index=models.Index(fields=['user', 'type'], name='recommendat_user_id_4ae1ec_idx'),
        ),
        migrations.AddIndex(
            model_name='productinteraction',
            index=models.Index(fields=['product', 'type'], name='recommendat_product_6ac8db_idx'),
        ),
        migrations.AddIndex(
            model_name='productinteraction',
            index=models.Index(fields=['user', '-created_at'], name='recommendat_user_id_405576_idx'),
        ),
        migrations.AddIndex(
            model_name='productsimilarity',
            index=models.Index(fields=['product_a', '-similarity_score'], name='recommendat_product_82a760_idx'),
        ),
        migrations.AddIndex(
            model_name='stockurgencysignal',
            index=models.Index(fields=['product', 'last_seen'], name='recommendat_product_ce8d61_idx'),
        ),
        migrations.AddIndex(
            model_name='userinterest',
            index=models.Index(fields=['user', '-score'], name='recommendat_user_id_303f2d_idx'),
        ),
        migrations.AddIndex(
            model_name='userinterest',
            index=models.Index(fields=['category'], name='recommendat_categor_9d2af2_idx'),
        ),
    ]
