# Generated by Django 6.0.1 on 2026-04-30 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_add_fraud_score'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentReconciliationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_at', models.DateTimeField(auto_now_add=True)),
                ('orders_checked', models.IntegerField(default=0)),
                ('discrepancies_found', models.IntegerField(default=0)),
                ('discrepancies_resolved', models.IntegerField(default=0)),
                ('errors', models.JSONField(default=list)),
                ('duration_seconds', models.FloatField(default=0)),
            ],
            options={
                'ordering': ['-run_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(db_index=True, max_length=50)),
                ('details', models.JSONField(default=dict)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='orders.payment')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['payment', 'event_type'], name='payments_pa_payment_5aac87_idx')],
            },
        ),
    ]
