# Generated by Django 6.0.1 on 2026-05-20 09:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_order_status'),
        ('payments', '0002_payment_events_reconciliation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='earningshold',
            name='disputed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earningshold',
            name='is_disputed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='earningshold',
            name='refunded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='earningshold',
            index=models.Index(fields=['is_disputed', 'released'], name='payments_ea_is_disp_79874c_idx'),
        ),
    ]
