# Generated by Django 6.0.1 on 2026-05-22 13:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_alter_orderitem_order_alter_orderstatuslog_order_and_more'),
        ('payments', '0003_earningshold_disputed_at_earningshold_is_disputed_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='earningshold',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='earnings_hold', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='earningshold',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='earnings_holds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paymentevent',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='orders.payment'),
        ),
    ]
