# Generated by Django 6.0.1 on 2026-05-24 19:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_order_tax_amount'),
        ('payments', '0004_alter_earningshold_order_alter_earningshold_seller_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chargeback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_case_id', models.CharField(max_length=120, unique=True)),
                ('reason_code', models.CharField(choices=[('fraud', 'Fraudulent transaction'), ('not_received', 'Goods not received'), ('not_as_described', 'Goods not as described'), ('duplicate', 'Duplicate charge'), ('subscription', 'Subscription cancellation'), ('other', 'Other')], default='other', max_length=20)),
                ('reason_text', models.TextField(blank=True, default='')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='AOA', max_length=8)),
                ('status', models.CharField(choices=[('received', 'Received — pending response'), ('evidence', 'Evidence submitted — awaiting issuer'), ('won', 'Won — funds retained'), ('lost', 'Lost — funds reversed'), ('accepted', 'Accepted — no contest')], db_index=True, default='received', max_length=10)),
                ('deadline_at', models.DateTimeField(db_index=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('evidence_packet', models.JSONField(default=dict)),
                ('admin_notes', models.TextField(blank=True, default='')),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chargebacks_handled', to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chargebacks', to='orders.payment')),
            ],
            options={
                'db_table': 'payments_chargeback',
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['status', '-received_at'], name='payments_ch_status_552b14_idx'), models.Index(fields=['deadline_at'], name='payments_ch_deadlin_3aae1a_idx')],
            },
        ),
    ]
