# Generated by Django 6.0.1 on 2026-05-24 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_chargeback'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettlementReconRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settlement_date', models.DateField(db_index=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('matched', models.PositiveIntegerField(default=0)),
                ('drift_rows', models.PositiveIntegerField(default=0)),
                ('unknown_rows', models.PositiveIntegerField(default=0)),
                ('total_gross', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_fees', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_net', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_drift', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'payments_settlement_recon_run',
                'ordering': ['-settlement_date'],
                'indexes': [models.Index(fields=['-settlement_date'], name='payments_se_settlem_59583a_idx')],
            },
        ),
        migrations.CreateModel(
            name='SettlementDrift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('drift', 'Amount drift (same ref, different amounts)'), ('unknown', 'Unknown reference (no PaymentEvent)')], max_length=10)),
                ('gateway_reference', models.CharField(db_index=True, max_length=200)),
                ('type', models.CharField(default='sale', help_text='sale|refund|chargeback|adjustment', max_length=20)),
                ('psp_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('ledger_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('drift_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('raw_row', models.JSONField(default=dict)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drifts', to='payments.settlementreconrun')),
            ],
            options={
                'db_table': 'payments_settlement_drift',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['gateway_reference'], name='payments_se_gateway_7308e4_idx'), models.Index(fields=['resolved', '-created_at'], name='payments_se_resolve_38c60c_idx')],
            },
        ),
    ]
