# Generated by Django 6.0.1 on 2026-05-24 19:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_order_tax_amount'),
        ('payments', '0006_settlementreconrun_settlementdrift'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AMLAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('threshold', 'Single transaction at/above threshold'), ('structuring', 'Structuring pattern (multi-tx aggregate)'), ('rapid_drain', 'Rapid wallet drain (inbound → immediate payout)'), ('manual', 'Manual flag by ops/admin')], db_index=True, max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open — pending review'), ('under_review', 'Under review by AML Officer'), ('reported', 'STR filed with FIU'), ('dismissed', 'Dismissed — cleared')], db_index=True, default='open', max_length=15)),
                ('aggregate_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('detector_payload', models.JSONField(default=dict, help_text='Detector raw output')),
                ('reason', models.TextField(blank=True, default='')),
                ('review_note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aml_alerts', to='orders.payment')),
                ('payout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aml_alerts', to='payments.payoutrequest')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aml_alerts_reviewed', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aml_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payments_aml_alert',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='payments_am_status_7341be_idx'), models.Index(fields=['user', 'kind'], name='payments_am_user_id_651e49_idx')],
            },
        ),
    ]
