# Generated by Django 6.0.1 on 2026-06-20 08:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_amlalert'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='sellerwallet',
            constraint=models.CheckConstraint(condition=models.Q(('balance__gte', 0), ('pending_balance__gte', 0)), name='ck_wallet_balance_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='wallettransaction',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='ck_wallet_txn_amount_positive'),
        ),
    ]
