# Generated by Django 6.0.1 on 2026-02-14 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_city_user_is_seller_user_is_verified_seller_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('warned', 'Warned'), ('suspended', 'Suspended'), ('banned', 'Banned')], default='active', max_length=10),
        ),
    ]
