# Generated by Django 6.0.1 on 2026-04-05 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0007_user_apple_id_user_currency_user_dark_mode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useractivitylog',
            name='location',
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='users_user_email_6f2530_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['referral_code'], name='users_user_referra_cff1f2_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['status', 'is_active'], name='users_user_status_7d9b11_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_seller', 'is_verified_seller'], name='users_user_is_sell_a0de5e_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivitylog',
            index=models.Index(fields=['user', '-created_at'], name='users_usera_user_id_5cb3ab_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['user', 'is_active'], name='users_users_user_id_3887fe_idx'),
        ),
    ]
