# Generated by Django 6.0.1 on 2026-04-27 15:52

import apps.payments.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_passwordhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pending_email',
            field=apps.payments.models.EncryptedCharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=apps.payments.models.EncryptedCharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='date_of_birth',
            field=apps.payments.models.EncryptedCharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='device',
            field=apps.payments.models.EncryptedCharField(blank=True, max_length=500),
        ),
    ]
