# Generated by Django 6.0.1 on 2026-05-22 13:28

import apps.payments.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_dailycheckin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='two_fa_secret',
            field=apps.payments.models.EncryptedCharField(blank=True, max_length=200, null=True),
        ),
    ]
