# Generated by Django 6.0.1 on 2026-05-30 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_userprofile_address_userprofile_business_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='jwt_version',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
