# Generated by Django 6.0.1 on 2026-04-22 14:07

import apps.listings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listing_city_listing_sale_type_alter_listing_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.TextField(blank=True, validators=[apps.listings.models.validate_listing_content]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='title',
            field=models.CharField(max_length=255, validators=[apps.listings.models.validate_listing_content]),
        ),
    ]
