# Generated by Django 6.0.1 on 2026-05-09 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('products', '0008_product_image_hash_productgroup_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariantCombo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('options', models.JSONField(default=dict, help_text='e.g. {"Color": "Red", "Size": "M"}')),
                ('price', models.DecimalField(decimal_places=2, help_text='Absolute price for this combo', max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('sku', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='variant_images/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_combos', to='products.product')),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['product', 'is_active'], name='inventory_p_product_49e2c0_idx')],
            },
        ),
    ]
