# Generated by Django 6.0.1 on 2026-05-20 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_productvariantcombo'),
        ('orders', '0011_alter_order_status'),
        ('products', '0010_add_search_vector'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stockreservation',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, max_length=128),
        ),
        migrations.AddField(
            model_name='stockreservation',
            name='variant_combo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='inventory.productvariantcombo'),
        ),
        migrations.AlterField(
            model_name='stockreservation',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='products.product'),
        ),
        migrations.AddIndex(
            model_name='stockreservation',
            index=models.Index(fields=['variant_combo', 'is_active'], name='inventory_s_variant_232a6f_idx'),
        ),
        migrations.AddIndex(
            model_name='stockreservation',
            index=models.Index(fields=['user', 'is_active'], name='inventory_s_user_id_73636f_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockreservation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('product__isnull', False), ('variant_combo__isnull', True)), models.Q(('product__isnull', True), ('variant_combo__isnull', False)), _connector='OR'), name='reservation_one_target'),
        ),
        migrations.AddConstraint(
            model_name='stockreservation',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), models.Q(('idempotency_key', ''), _negated=True)), fields=('user', 'idempotency_key'), name='uniq_user_active_idem_key'),
        ),
    ]
