# Generated by Django 6.0.1 on 2026-06-03 08:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceFingerprint',
            fields=[
                ('fingerprint_hash', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('raw_ua', models.CharField(blank=True, default='', max_length=255)),
                ('timezone', models.CharField(blank=True, default='', max_length=64)),
                ('language', models.CharField(blank=True, default='', max_length=24)),
                ('screen', models.CharField(blank=True, default='', max_length=32)),
                ('platform', models.CharField(blank=True, default='', max_length=32)),
                ('canvas_hash', models.CharField(blank=True, default='', max_length=64)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('seen_count', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='IpReputation',
            fields=[
                ('ip_address', models.GenericIPAddressField(primary_key=True, serialize=False)),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('external_score', models.PositiveSmallIntegerField(default=0)),
                ('distinct_users_24h', models.PositiveSmallIntegerField(default=0)),
                ('failed_logins_1h', models.PositiveSmallIntegerField(default=0)),
                ('chargebacks_30d', models.PositiveSmallIntegerField(default=0)),
                ('is_datacenter', models.BooleanField(default=False)),
                ('is_tor', models.BooleanField(default=False)),
                ('is_proxy', models.BooleanField(default=False)),
                ('is_manual_block', models.BooleanField(default=False)),
                ('country', models.CharField(blank=True, default='', max_length=2)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VelocityRule',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('action', models.CharField(choices=[('welcome_grant', 'Welcome incentive grant'), ('referral_click', 'Referral link click'), ('referral_register', 'Referral-driven registration'), ('checkout_submit', 'Checkout submission'), ('order_place', 'Order place'), ('payment_attempt', 'Payment attempt'), ('coupon_redeem', 'Coupon redemption'), ('dispute_open', 'Dispute open'), ('account_login', 'Login'), ('signup', 'Signup')], db_index=True, max_length=24)),
                ('is_active', models.BooleanField(default=True)),
                ('scope', models.CharField(choices=[('user', 'Per user'), ('device', 'Per device fingerprint'), ('ip', 'Per IP address'), ('email', 'Per email')], max_length=16)),
                ('window_seconds', models.PositiveIntegerField(default=3600)),
                ('max_count', models.PositiveIntegerField(default=10)),
                ('on_exceed', models.CharField(choices=[('allow', 'Allow'), ('review', 'Send for manual review'), ('challenge', 'Challenge (OTP / step-up)'), ('block', 'Block — refuse the action')], default='review', max_length=12)),
                ('score_weight', models.PositiveSmallIntegerField(default=25, help_text='Points to add to the fraud score if this rule trips.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('welcome_grant', 'Welcome incentive grant'), ('referral_click', 'Referral link click'), ('referral_register', 'Referral-driven registration'), ('checkout_submit', 'Checkout submission'), ('order_place', 'Order place'), ('payment_attempt', 'Payment attempt'), ('coupon_redeem', 'Coupon redemption'), ('dispute_open', 'Dispute open'), ('account_login', 'Login'), ('signup', 'Signup')], db_index=True, max_length=24)),
                ('device_hash', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('occurred_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fraud_action_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['action', 'user', 'occurred_at'], name='fraud_engin_action_17bc55_idx'), models.Index(fields=['action', 'device_hash', 'occurred_at'], name='fraud_engin_action_8a5315_idx'), models.Index(fields=['action', 'ip_address', 'occurred_at'], name='fraud_engin_action_d47555_idx')],
            },
        ),
        migrations.CreateModel(
            name='DeviceUserLink',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('seen_count', models.PositiveIntegerField(default=1)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_links', to='fraud_engine.devicefingerprint')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user'], name='fraud_engin_user_id_bc4c4f_idx')],
                'unique_together': {('device', 'user')},
            },
        ),
        migrations.CreateModel(
            name='FraudDecision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('welcome_grant', 'Welcome incentive grant'), ('referral_click', 'Referral link click'), ('referral_register', 'Referral-driven registration'), ('checkout_submit', 'Checkout submission'), ('order_place', 'Order place'), ('payment_attempt', 'Payment attempt'), ('coupon_redeem', 'Coupon redemption'), ('dispute_open', 'Dispute open'), ('account_login', 'Login'), ('signup', 'Signup')], db_index=True, max_length=24)),
                ('device_hash', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('decision', models.CharField(choices=[('allow', 'Allow'), ('review', 'Send for manual review'), ('challenge', 'Challenge (OTP / step-up)'), ('block', 'Block — refuse the action')], default='allow', max_length=12)),
                ('reasons', models.JSONField(blank=True, default=list)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fraud_decisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action', 'decision'], name='fraud_engin_action_24cbd6_idx')],
            },
        ),
    ]
