# Generated by Django 6.0.1 on 2026-06-19 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments_angola', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedWebhookEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('provider', models.CharField(db_index=True, default='appypay', max_length=40)),
                ('event_key', models.CharField(db_index=True, max_length=128, unique=True)),
                ('merchant_order_id', models.CharField(blank=True, max_length=120)),
                ('psp_status', models.CharField(blank=True, max_length=40)),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'indexes': [models.Index(fields=['provider', '-received_at'], name='payments_an_provide_c8d974_idx')],
            },
        ),
    ]
