# Generated by Django 6.0.1 on 2026-05-17 20:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sha256', models.CharField(db_index=True, max_length=64, unique=True)),
                ('original_path', models.CharField(max_length=500)),
                ('content_type', models.CharField(default='image/jpeg', max_length=40)),
                ('width', models.PositiveIntegerField(default=0)),
                ('height', models.PositiveIntegerField(default=0)),
                ('bytes_size', models.PositiveBigIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending generation'), ('ready', 'All variants generated'), ('partial', 'Some variants generated, some failed'), ('failed', 'Could not generate (corrupt source?)'), ('deleted', 'Soft-deleted')], db_index=True, default='pending', max_length=10)),
                ('last_error', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImageVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant', models.CharField(max_length=10)),
                ('format', models.CharField(max_length=8)),
                ('storage_path', models.CharField(max_length=500)),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('bytes_size', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='imagery.imagesource')),
            ],
        ),
        migrations.AddIndex(
            model_name='imagesource',
            index=models.Index(fields=['status', '-created_at'], name='imagery_ima_status_159a91_idx'),
        ),
        migrations.AddIndex(
            model_name='imagevariant',
            index=models.Index(fields=['source', 'variant'], name='imagery_ima_source__8e0887_idx'),
        ),
        migrations.AddConstraint(
            model_name='imagevariant',
            constraint=models.UniqueConstraint(fields=('source', 'variant', 'format'), name='uniq_source_variant_format'),
        ),
    ]
