# Generated by Django 6.0.1 on 2026-07-05 18:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_id', models.CharField(db_index=True, max_length=128, unique=True)),
                ('locale', models.JSONField(blank=True, default=dict)),
                ('interests', models.JSONField(blank=True, default=list)),
                ('permissions', models.JSONField(blank=True, default=dict)),
                ('attribution', models.JSONField(blank=True, default=dict)),
                ('onboarding_status', models.CharField(choices=[('not_started', 'Not started'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('skipped', 'Skipped')], db_index=True, default='not_started', max_length=16)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('carried_over_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guest_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'onboarding_guest_profile',
                'indexes': [models.Index(fields=['linked_user'], name='onboarding__linked__b5dbd8_idx'), models.Index(fields=['onboarding_status', '-created_at'], name='onboarding__onboard_6d8f2b_idx')],
            },
        ),
    ]
