# Generated by Django 6.0.1 on 2026-07-06 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestCartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.PositiveBigIntegerField()),
                ('variant_combo_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price_at_add', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='onboarding.guestprofile')),
            ],
            options={
                'db_table': 'onboarding_guest_cart_item',
                'constraints': [models.UniqueConstraint(fields=('guest', 'product_id', 'variant_combo_id'), name='guest_cart_item_unique'), models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='guest_cart_item_qty_positive')],
            },
        ),
    ]
