# Generated by Django 6.0.1 on 2026-06-10 20:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlashDealDiscoverySnapshot',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_slug', models.CharField(db_index=True, max_length=64)),
                ('deals', models.JSONField(blank=True, default=list)),
                ('total_deals', models.PositiveIntegerField(default=0)),
                ('soonest_ending_at', models.DateTimeField(blank=True, null=True)),
                ('computed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewArrivalEntry',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('product_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('category_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('quality_score', models.FloatField(default=0)),
                ('gate_passed', models.BooleanField(default=False)),
                ('gate_failures', models.JSONField(blank=True, default=list)),
                ('freshness_score', models.FloatField(default=1.0)),
                ('listed_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('admitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='QueryParse',
            fields=[
                ('query_hash', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('raw_query', models.CharField(max_length=200)),
                ('normalised_query', models.CharField(max_length=200)),
                ('detected_entities', models.JSONField(blank=True, default=dict)),
                ('predicted_category_id', models.CharField(blank=True, default='', max_length=64)),
                ('category_confidence', models.FloatField(default=0)),
                ('extracted_filters', models.JSONField(blank=True, default=dict)),
                ('language', models.CharField(default='pt-AO', max_length=10)),
                ('parsed_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegionalSurfacingRule',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=2, unique=True)),
                ('local_warehouse_boost', models.FloatField(default=1.5)),
                ('domestic_seller_boost', models.FloatField(default=1.2)),
                ('fast_delivery_days_threshold', models.PositiveSmallIntegerField(default=3)),
                ('fast_delivery_boost', models.FloatField(default=1.3)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SearchExperiment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('hypothesis', models.TextField(blank=True, default='')),
                ('ranking_config_control', models.JSONField(blank=True, default=dict)),
                ('ranking_config_variant', models.JSONField(blank=True, default=dict)),
                ('traffic_pct', models.PositiveSmallIntegerField(default=50)),
                ('primary_metric', models.CharField(default='ctr', max_length=40)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('running', 'Running'), ('analysing', 'Analysing'), ('shipped', 'Shipped — variant won'), ('reverted', 'Reverted — control won')], default='draft', max_length=12)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('result_summary', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SearchKpiSnapshot',
            fields=[
                ('snapshot_date', models.DateField(primary_key=True, serialize=False)),
                ('total_searches', models.PositiveIntegerField(default=0)),
                ('zero_results_pct', models.FloatField(default=0)),
                ('search_ctr', models.FloatField(default=0)),
                ('search_to_cart_pct', models.FloatField(default=0)),
                ('search_to_purchase_pct', models.FloatField(default=0)),
                ('avg_click_position', models.FloatField(default=0)),
                ('autocomplete_usage_pct', models.FloatField(default=0)),
                ('voice_searches', models.PositiveIntegerField(default=0)),
                ('visual_searches', models.PositiveIntegerField(default=0)),
                ('trending_feed_ctr', models.FloatField(default=0)),
                ('digest_open_rate', models.FloatField(default=0)),
                ('digest_click_rate', models.FloatField(default=0)),
                ('comparison_sessions', models.PositiveIntegerField(default=0)),
                ('active_experiments', models.PositiveSmallIntegerField(default=0)),
                ('by_language', models.JSONField(blank=True, default=dict)),
                ('by_country', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SoldCountDisplayRule',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('country', models.CharField(blank=True, default='', max_length=2, unique=True)),
                ('min_display', models.PositiveIntegerField(default=10)),
                ('bands', models.JSONField(default=list, help_text='[{"min": 1000, "label": "1K+"}, ...] descending order.')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AttributeSchema',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('category_id', models.CharField(db_index=True, max_length=64)),
                ('attribute_key', models.CharField(max_length=64)),
                ('display_name', models.CharField(max_length=120)),
                ('data_type', models.CharField(choices=[('string', 'String'), ('number', 'Number'), ('boolean', 'Boolean'), ('enum', 'Enum')], default='string', max_length=12)),
                ('unit', models.CharField(blank=True, default='', max_length=20)),
                ('synonyms', models.JSONField(blank=True, default=list)),
                ('importance_rank', models.PositiveSmallIntegerField(default=50)),
            ],
            options={
                'unique_together': {('category_id', 'attribute_key')},
            },
        ),
        migrations.CreateModel(
            name='AutocompleteSuggestion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('prefix', models.CharField(db_index=True, max_length=60)),
                ('suggestion', models.CharField(max_length=200)),
                ('rank', models.PositiveSmallIntegerField()),
                ('source', models.CharField(choices=[('organic', 'Organic — query log'), ('curated', 'Curated'), ('trending', 'Trending'), ('category', 'Category')], default='organic', max_length=12)),
                ('search_count', models.PositiveIntegerField(default=0)),
                ('language', models.CharField(default='pt-AO', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'unique_together': {('prefix', 'rank', 'language')},
            },
        ),
        migrations.CreateModel(
            name='BestsellerBadge',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('product_id', models.CharField(db_index=True, max_length=64)),
                ('category_id', models.CharField(db_index=True, max_length=64)),
                ('country', models.CharField(blank=True, default='', max_length=2)),
                ('rank', models.PositiveSmallIntegerField()),
                ('score', models.FloatField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('category_id', 'country', 'rank')},
            },
        ),
        migrations.CreateModel(
            name='CoClickEdge',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('query_a', models.CharField(db_index=True, max_length=200)),
                ('query_b', models.CharField(db_index=True, max_length=200)),
                ('co_click_count', models.PositiveIntegerField(default=0)),
                ('strength', models.FloatField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('query_a', 'query_b')},
            },
        ),
        migrations.CreateModel(
            name='CrossCategoryAffinity',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('source_category_id', models.CharField(db_index=True, max_length=64)),
                ('target_category_id', models.CharField(db_index=True, max_length=64)),
                ('co_purchase_count', models.PositiveIntegerField(default=0)),
                ('affinity_score', models.FloatField(default=0)),
                ('sample_product_pairs', models.JSONField(blank=True, default=list)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('source_category_id', 'target_category_id')},
            },
        ),
        migrations.CreateModel(
            name='EditorialCollection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, default='', max_length=255)),
                ('hero_image_key', models.CharField(blank=True, default='', max_length=255)),
                ('product_ids', models.JSONField(default=list)),
                ('country_scope', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('live', 'Live'), ('archived', 'Archived')], default='draft', max_length=12)),
                ('live_from', models.DateTimeField(blank=True, null=True)),
                ('live_until', models.DateTimeField(blank=True, null=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('click_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('curator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curated_collections', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EditorialSlot',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('surface', models.CharField(choices=[('home_hero', 'Home hero'), ('home_row', 'Home row'), ('category_banner', 'Category banner'), ('search_banner', 'Search banner'), ('flash_tab', 'Flash tab')], max_length=24)),
                ('position', models.PositiveSmallIntegerField(default=1)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='search_discovery.editorialcollection')),
            ],
        ),
        migrations.CreateModel(
            name='EmailDigestRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('week_start', models.DateField(db_index=True)),
                ('item_count', models.PositiveSmallIntegerField(default=0)),
                ('personalisation_basis', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('generated', 'Generated'), ('sent', 'Sent'), ('skipped', 'Skipped — no items'), ('failed', 'Failed')], default='generated', max_length=12)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_digests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'week_start')},
            },
        ),
        migrations.CreateModel(
            name='EmailDigestItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('product_id', models.CharField(max_length=64)),
                ('slot', models.PositiveSmallIntegerField()),
                ('reason', models.CharField(choices=[('viewed_similar', 'Viewed similar'), ('price_dropped', 'Price dropped'), ('trending', 'Trending'), ('back_in_stock', 'Back in stock'), ('category_affinity', 'Category affinity'), ('wishlist', 'In wishlist')], max_length=24)),
                ('clicked', models.BooleanField(default=False)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='search_discovery.emaildigestrun')),
            ],
        ),
        migrations.CreateModel(
            name='ProductComparison',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_ids', models.JSONField(default=list)),
                ('category_id', models.CharField(blank=True, default='', max_length=64)),
                ('comparison_matrix', models.JSONField(blank=True, default=dict)),
                ('differences_highlighted', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_comparisons', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RelatedSearch',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('source_query', models.CharField(db_index=True, max_length=200)),
                ('related_query', models.CharField(max_length=200)),
                ('rank', models.PositiveSmallIntegerField()),
                ('strength', models.FloatField(default=0)),
                ('computed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('source_query', 'rank')},
            },
        ),
        migrations.CreateModel(
            name='SearchDiscoveryEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('kind', models.CharField(db_index=True, max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sd_audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrendingScore',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('product_id', models.CharField(db_index=True, max_length=64)),
                ('category_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('country', models.CharField(blank=True, db_index=True, default='', max_length=2)),
                ('velocity_1h', models.FloatField(default=0)),
                ('velocity_24h', models.FloatField(default=0)),
                ('velocity_7d_baseline', models.FloatField(default=0)),
                ('acceleration', models.FloatField(default=0, help_text='velocity_1h vs 7d baseline ratio — the trending signal.')),
                ('view_to_purchase_rate', models.FloatField(default=0)),
                ('score', models.FloatField(db_index=True, default=0)),
                ('computed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'indexes': [models.Index(fields=['country', '-score'], name='search_disc_country_e0ba92_idx')],
            },
        ),
        migrations.CreateModel(
            name='VerifiedBadge',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('badge_type', models.CharField(choices=[('official_brand', 'Official Brand Store'), ('verified_seller', 'Verified Seller'), ('top_rated', 'Top Rated'), ('fast_shipper', 'Fast Shipper'), ('choice', 'MICHA Choice'), ('local_warehouse', 'Local Warehouse')], max_length=20)),
                ('eligibility_snapshot', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoke_reason', models.CharField(blank=True, default='', max_length=120)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discovery_badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('seller', 'badge_type')},
            },
        ),
        migrations.CreateModel(
            name='BadgeIntegrityCheck',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('still_eligible', models.BooleanField()),
                ('metrics_snapshot', models.JSONField(blank=True, default=dict)),
                ('action_taken', models.CharField(choices=[('none', 'None'), ('warned', 'Warned'), ('revoked', 'Revoked')], default='none', max_length=16)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrity_checks', to='search_discovery.verifiedbadge')),
            ],
        ),
        migrations.CreateModel(
            name='VisualSearchLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('image_key', models.CharField(max_length=255)),
                ('detected_objects', models.JSONField(blank=True, default=list)),
                ('matched_product_ids', models.JSONField(blank=True, default=list)),
                ('top_match_confidence', models.FloatField(default=0)),
                ('results_count', models.PositiveIntegerField(default=0)),
                ('clicked_result', models.BooleanField(default=False)),
                ('occurred_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visual_searches', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VoiceSearchLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('audio_duration_ms', models.PositiveIntegerField(default=0)),
                ('transcribed_text', models.CharField(max_length=500)),
                ('stt_confidence', models.FloatField(default=0)),
                ('language', models.CharField(default='pt-AO', max_length=10)),
                ('results_count', models.PositiveIntegerField(default=0)),
                ('clicked_result', models.BooleanField(default=False)),
                ('occurred_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voice_searches', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ZeroResultsLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('query', models.CharField(db_index=True, max_length=200)),
                ('language', models.CharField(default='pt-AO', max_length=10)),
                ('country', models.CharField(blank=True, default='', max_length=2)),
                ('fallback_strategy', models.CharField(blank=True, choices=[('broadened', 'Broadened terms'), ('spell_corrected', 'Spell corrected'), ('category_suggest', 'Category suggestion'), ('synonym_expand', 'Synonym expansion'), ('none', 'No fallback found')], default='', max_length=20)),
                ('fallback_results_count', models.PositiveIntegerField(default=0)),
                ('converted', models.BooleanField(default=False)),
                ('occurred_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zero_result_searches', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IntentSignal',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('session_id', models.CharField(blank=True, default='', max_length=64)),
                ('product_id', models.CharField(db_index=True, max_length=64)),
                ('kind', models.CharField(choices=[('dwell_long', 'Long dwell on PDP'), ('image_zoom', 'Zoomed images'), ('spec_expand', 'Expanded specifications'), ('review_read', 'Read reviews'), ('size_check', 'Checked size guide'), ('shipping_check', 'Checked shipping estimate'), ('share', 'Shared product'), ('re_visit', 'Re-visited PDP'), ('cart_hesitation', 'Added + removed from cart')], max_length=20)),
                ('value', models.FloatField(default=0)),
                ('occurred_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intent_signals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'product_id'], name='search_disc_user_id_f37e79_idx')],
            },
        ),
        migrations.CreateModel(
            name='SearchClickLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('query', models.CharField(db_index=True, max_length=200)),
                ('session_id', models.CharField(blank=True, default='', max_length=64)),
                ('product_id', models.CharField(db_index=True, max_length=64)),
                ('position', models.PositiveSmallIntegerField()),
                ('page', models.PositiveSmallIntegerField(default=1)),
                ('experiment_bucket', models.CharField(blank=True, default='', max_length=8)),
                ('action', models.CharField(choices=[('impression', 'Impression'), ('click', 'Click'), ('add_to_cart', 'Add to cart'), ('purchase', 'Purchase')], default='click', max_length=12)),
                ('occurred_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_clicks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['query', 'action'], name='search_disc_query_55637a_idx')],
            },
        ),
        migrations.CreateModel(
            name='ExperimentAssignment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('bucket', models.CharField(choices=[('control', 'Control'), ('variant', 'Variant')], max_length=8)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_experiment_assignments', to=settings.AUTH_USER_MODEL)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='search_discovery.searchexperiment')),
            ],
            options={
                'unique_together': {('experiment', 'user')},
            },
        ),
        migrations.CreateModel(
            name='SellerRankingSignal',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('snapshot_date', models.DateField(db_index=True)),
                ('fulfilment_score', models.FloatField(default=0)),
                ('service_score', models.FloatField(default=0)),
                ('quality_score', models.FloatField(default=0)),
                ('trust_score', models.FloatField(default=0)),
                ('composite_multiplier', models.FloatField(default=1.0)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranking_signals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('seller', 'snapshot_date')},
            },
        ),
    ]
