# Generated by Django 6.0.1 on 2026-04-29 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(db_index=True, max_length=200)),
                ('task_id', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('started', 'Started'), ('success', 'Success'), ('failure', 'Failure'), ('retry', 'Retry')], db_index=True, max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('retries', models.IntegerField(default=0)),
                ('result_summary', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['task_name', '-started_at'], name='monitoring__task_na_adf5f4_idx'), models.Index(fields=['status', '-started_at'], name='monitoring__status_1c4c43_idx')],
            },
        ),
    ]
