# Generated by Django 6.0.1 on 2026-05-09 21:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('user_store_credit', 'User · Store credit (loyalty Kz)'), ('user_loyalty_points', 'User · Loyalty points'), ('seller_wallet', 'Seller · Wallet (payout-eligible)'), ('seller_pending', 'Seller · Pending (in escrow)'), ('platform_revenue', 'Platform · Revenue (commission)'), ('platform_loyalty_fund', 'Platform · Loyalty fund (counter for credits awarded to users)'), ('platform_refund_pool', 'Platform · Refund pool'), ('platform_fee_gateway', 'Platform · Gateway fees collected'), ('buyer_payments', 'Buyer · Payments received (clearing)'), ('external_clearing', 'External clearing (payment gateway)')], db_index=True, max_length=40)),
                ('currency', models.CharField(default='AOA', max_length=3)),
                ('name', models.CharField(blank=True, help_text='Optional human-readable label', max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('cached_balance_cents', models.BigIntegerField(default=0)),
                ('cached_balance_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, help_text='Null for platform / singleton accounts', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', models.CharField(db_index=True, max_length=200, unique=True)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('ref_type', models.CharField(blank=True, db_index=True, help_text='e.g. "order", "checkin", "refund"', max_length=40)),
                ('ref_id', models.CharField(blank=True, db_index=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit_cents', models.BigIntegerField(default=0)),
                ('credit_cents', models.BigIntegerField(default=0)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='ledger.account')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='ledger.journal')),
            ],
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['type', 'user'], name='ledger_acco_type_1ed6ba_idx'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('type', 'user'), name='ledger_account_unique_per_user_type'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', True)), fields=('type',), name='ledger_account_singleton_platform_type'),
        ),
        migrations.AddIndex(
            model_name='journal',
            index=models.Index(fields=['ref_type', 'ref_id', '-created_at'], name='ledger_jour_ref_typ_c2763c_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['account', '-created_at'], name='ledger_ledg_account_34c609_idx'),
        ),
        migrations.AddConstraint(
            model_name='ledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(('debit_cents__gte', 0), ('credit_cents__gte', 0), models.Q(('credit_cents', 0), ('debit_cents', 0), _negated=True), models.Q(('debit_cents', 0), ('credit_cents', 0), _connector='OR')), name='ledger_entry_exactly_one_direction'),
        ),
    ]
