# Generated by Django 6.0.1 on 2026-05-23 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0010_add_search_vector'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('target_id', models.CharField(blank=True, max_length=100)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_admin_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdminActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('suspend_user', 'Suspend User'), ('ban_user', 'Ban User'), ('activate_user', 'Activate User'), ('approve_verification', 'Approve Verification'), ('reject_verification', 'Reject Verification'), ('approve_payout', 'Approve Payout'), ('reject_payout', 'Reject Payout'), ('resolve_dispute_buyer', 'Resolve Dispute (Buyer)'), ('resolve_dispute_seller', 'Resolve Dispute (Seller)'), ('remove_product', 'Remove Product'), ('feature_product', 'Feature Product'), ('set_commission', 'Set Commission Rate'), ('issue_refund', 'Issue Refund'), ('create_announcement', 'Create Announcement'), ('assign_role', 'Assign Role'), ('revoke_role', 'Revoke Role'), ('view_encrypted_data', 'View Encrypted Data')], max_length=50)),
                ('target_type', models.CharField(max_length=50)),
                ('target_id', models.CharField(max_length=100)),
                ('target_repr', models.CharField(blank=True, max_length=200)),
                ('note', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=200)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admin_actions_taken', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['admin', '-created_at'], name='admin_actio_admin_i_8d0548_idx'), models.Index(fields=['action', '-created_at'], name='admin_actio_action_641d30_idx'), models.Index(fields=['target_type', 'target_id'], name='admin_actio_target__059266_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductModeration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='pending', max_length=10)),
                ('rejection_reason', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='moderation', to='products.product')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='admin_actio_status_022125_idx')],
            },
        ),
    ]
