# Generated by Django 6.0.1 on 2026-06-27 16:29

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_actions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='adminactionlog',
            name='entry_hash',
            field=models.CharField(blank=True, db_index=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='adminactionlog',
            name='outcome',
            field=models.CharField(choices=[('success', 'Success'), ('failure', 'Failure'), ('denied', 'Denied')], default='success', max_length=16),
        ),
        migrations.AddField(
            model_name='adminactionlog',
            name='prev_hash',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='adminactionlog',
            name='seq',
            field=models.PositiveBigIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='adminactionlog',
            name='action',
            field=models.CharField(choices=[('suspend_user', 'Suspend User'), ('ban_user', 'Ban User'), ('activate_user', 'Activate User'), ('approve_verification', 'Approve Verification'), ('reject_verification', 'Reject Verification'), ('approve_payout', 'Approve Payout'), ('reject_payout', 'Reject Payout'), ('resolve_dispute_buyer', 'Resolve Dispute (Buyer)'), ('resolve_dispute_seller', 'Resolve Dispute (Seller)'), ('remove_product', 'Remove Product'), ('feature_product', 'Feature Product'), ('set_commission', 'Set Commission Rate'), ('issue_refund', 'Issue Refund'), ('create_announcement', 'Create Announcement'), ('assign_role', 'Assign Role'), ('revoke_role', 'Revoke Role'), ('view_encrypted_data', 'View Encrypted Data'), ('moderate_approve', 'Moderate: Approve (dismiss flag)'), ('moderate_reject', 'Moderate: Reject (remove content)'), ('moderate_escalate', 'Moderate: Escalate (senior review)')], max_length=50),
        ),
        migrations.AlterField(
            model_name='adminactionlog',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='adminactionlog',
            index=models.Index(fields=['seq'], name='admin_actio_seq_6ac796_idx'),
        ),
    ]
