# Generated by Django 6.0.1 on 2026-07-07 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_actions', '0003_backfill_audit_chain'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRestriction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_selling', models.BooleanField(default=False)),
                ('no_withdrawal', models.BooleanField(default=False)),
                ('no_messaging', models.BooleanField(default=False)),
                ('reason', models.CharField(blank=True, max_length=300)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restricted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restrictions_applied', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='restriction', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'admin_user_restriction',
            },
        ),
    ]
