# Generated by Django 6.0.1 on 2026-05-29 05:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('ship_from_country', models.CharField(default='Angola', max_length=80)),
                ('processing_days', models.PositiveIntegerField(default=2)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShippingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('standard', 'Standard'), ('express', 'Express'), ('economy', 'Economy'), ('dhl', 'DHL'), ('fedex', 'FedEx'), ('ups', 'UPS'), ('local_post', 'Local Post'), ('custom', 'Custom')], default='standard', max_length=20)),
                ('custom_service_name', models.CharField(blank=True, max_length=80)),
                ('destinations', models.JSONField(default=list)),
                ('min_days', models.PositiveIntegerField(default=1)),
                ('max_days', models.PositiveIntegerField(default=7)),
                ('free_shipping', models.BooleanField(default=False)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('additional_item_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='methods', to='shipping.shippingtemplate')),
            ],
            options={
                'ordering': ['ordering', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='shippingtemplate',
            index=models.Index(fields=['seller', 'is_default'], name='shipping_sh_seller__464169_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='shippingtemplate',
            unique_together={('seller', 'name')},
        ),
    ]
