# Generated by Django 6.0.1 on 2026-05-16 07:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FXRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_currency', models.CharField(db_index=True, max_length=5)),
                ('target_currency', models.CharField(db_index=True, max_length=5)),
                ('rate', models.DecimalField(decimal_places=8, max_digits=20)),
                ('source', models.CharField(choices=[('manual', 'Manual (admin override)'), ('bna_api', 'BNA (Banco Nacional de Angola) API'), ('external', 'External feed (e.g. OXR, fixer.io)'), ('inferred', 'Inferred from inverse / cross-rate')], max_length=12)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('valid_from', models.DateTimeField(db_index=True)),
                ('valid_until', models.DateTimeField(blank=True, db_index=True, help_text='NULL = currently in effect', null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fx_rates_recorded', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConversionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_currency', models.CharField(db_index=True, max_length=5)),
                ('to_currency', models.CharField(db_index=True, max_length=5)),
                ('amount_from', models.DecimalField(decimal_places=8, max_digits=20)),
                ('amount_to', models.DecimalField(decimal_places=8, max_digits=20)),
                ('rate_applied', models.DecimalField(decimal_places=8, max_digits=20)),
                ('ref_type', models.CharField(blank=True, db_index=True, max_length=40)),
                ('ref_id', models.CharField(blank=True, db_index=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('fx_rate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conversion_events', to='fx.fxrate')),
            ],
        ),
        migrations.AddIndex(
            model_name='fxrate',
            index=models.Index(fields=['source_currency', 'target_currency', 'valid_until'], name='fx_fxrate_source__099036_idx'),
        ),
        migrations.AddIndex(
            model_name='fxrate',
            index=models.Index(fields=['source_currency', 'target_currency', 'valid_from'], name='fx_fxrate_source__9af063_idx'),
        ),
        migrations.AddConstraint(
            model_name='fxrate',
            constraint=models.UniqueConstraint(condition=models.Q(('valid_until__isnull', True)), fields=('source_currency', 'target_currency'), name='uniq_current_fx_rate'),
        ),
        migrations.AddConstraint(
            model_name='fxrate',
            constraint=models.CheckConstraint(condition=models.Q(('rate__gt', 0)), name='fx_rate_positive'),
        ),
        migrations.AddIndex(
            model_name='conversionevent',
            index=models.Index(fields=['ref_type', 'ref_id'], name='fx_conversi_ref_typ_2f4b1b_idx'),
        ),
        migrations.AddIndex(
            model_name='conversionevent',
            index=models.Index(fields=['from_currency', 'to_currency', '-created_at'], name='fx_conversi_from_cu_3e844a_idx'),
        ),
    ]
