# Generated by Django 6.0.1 on 2026-05-20 09:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disputes', '0001_initial'),
        ('orders', '0011_alter_order_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dispute',
            name='auto_resolve_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dispute',
            name='evidence_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='dispute',
            name='last_seller_message_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dispute',
            name='respond_by',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='dispute',
            index=models.Index(fields=['status', 'auto_resolve_at'], name='disputes_di_status_e3f147_idx'),
        ),
    ]
