# Generated by Django 6.0.1 on 2026-05-15 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Saga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Saga definition name, registered in code', max_length=80)),
                ('ref_type', models.CharField(blank=True, db_index=True, max_length=40)),
                ('ref_id', models.CharField(blank=True, db_index=True, max_length=80)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('waiting', 'Waiting (parked)'), ('completed', 'Completed'), ('compensating', 'Compensating'), ('failed', 'Failed (compensated cleanly)'), ('needs_attention', 'Needs operator attention'), ('abandoned', 'Abandoned (timeout)')], db_index=True, default='pending', max_length=20)),
                ('payload', models.JSONField(default=dict)),
                ('current_step', models.PositiveIntegerField(default=0)),
                ('steps_log', models.JSONField(default=list)),
                ('error', models.TextField(blank=True)),
                ('wait_until', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'wait_until'], name='sagas_saga_status_a0ba93_idx'), models.Index(fields=['name', 'status'], name='sagas_saga_name_893e26_idx'), models.Index(fields=['ref_type', 'ref_id'], name='sagas_saga_ref_typ_590b70_idx')],
            },
        ),
    ]
