# Generated by Django 6.0.1 on 2026-05-16 07:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxJurisdiction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(help_text='ISO 3166-1 alpha-2, e.g. AO', max_length=2)),
                ('province_code', models.CharField(blank=True, default='', max_length=6)),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['country_code', 'province_code'],
                'indexes': [models.Index(fields=['country_code', 'province_code'], name='tax_taxjuri_country_5e2169_idx')],
                'constraints': [models.UniqueConstraint(fields=('country_code', 'province_code'), name='uniq_jurisdiction_country_province')],
            },
        ),
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='VAT', help_text='Display name, e.g. VAT / IVA', max_length=40)),
                ('rate', models.DecimalField(decimal_places=4, help_text='As a fraction — 0.14 = 14%', max_digits=6)),
                ('source', models.CharField(choices=[('manual', 'Manual (admin-set)'), ('regulator', 'Regulator publication'), ('import', 'Imported from external feed')], default='manual', max_length=12)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('valid_from', models.DateTimeField(db_index=True)),
                ('valid_until', models.DateTimeField(blank=True, db_index=True, help_text='NULL = currently in effect', null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('jurisdiction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='tax.taxjurisdiction')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TaxCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_type', models.CharField(db_index=True, max_length=40)),
                ('ref_id', models.CharField(db_index=True, max_length=80)),
                ('ship_to_country', models.CharField(max_length=2)),
                ('ship_to_province', models.CharField(blank=True, max_length=6)),
                ('rate_applied', models.DecimalField(decimal_places=4, max_digits=6)),
                ('breakdown', models.JSONField(default=dict)),
                ('total_taxable', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total_tax', models.DecimalField(decimal_places=2, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('jurisdiction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tax.taxjurisdiction')),
                ('tax_rate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tax.taxrate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaxCategoryRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('STANDARD', 'Standard'), ('REDUCED', 'Reduced'), ('ZERO', 'Zero-rated'), ('EXEMPT', 'Exempt')], max_length=10)),
                ('multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=4)),
                ('jurisdiction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_rules', to='tax.taxjurisdiction')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('jurisdiction', 'category'), name='uniq_jurisdiction_category')],
            },
        ),
        migrations.AddIndex(
            model_name='taxrate',
            index=models.Index(fields=['jurisdiction', 'valid_until'], name='tax_taxrate_jurisdi_e39529_idx'),
        ),
        migrations.AddIndex(
            model_name='taxrate',
            index=models.Index(fields=['jurisdiction', 'valid_from'], name='tax_taxrate_jurisdi_d2a00f_idx'),
        ),
        migrations.AddConstraint(
            model_name='taxrate',
            constraint=models.UniqueConstraint(condition=models.Q(('valid_until__isnull', True)), fields=('jurisdiction',), name='uniq_current_tax_rate'),
        ),
        migrations.AddConstraint(
            model_name='taxrate',
            constraint=models.CheckConstraint(condition=models.Q(('rate__gte', 0), ('rate__lte', 1)), name='tax_rate_in_range'),
        ),
        migrations.AddIndex(
            model_name='taxcalculation',
            index=models.Index(fields=['ref_type', 'ref_id'], name='tax_taxcalc_ref_typ_0f222d_idx'),
        ),
    ]
