# Generated by Django 6.0.1 on 2026-05-17 10:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('code_prefix', models.CharField(db_index=True, max_length=4)),
                ('initial_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('current_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='AOA', max_length=3)),
                ('status', models.CharField(choices=[('active', 'Active'), ('redeemed', 'Fully redeemed'), ('expired', 'Expired'), ('cancelled', 'Cancelled by admin')], db_index=True, default='active', max_length=10)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, help_text='NULL = never expires', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('claimed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gift_cards_owned', to=settings.AUTH_USER_MODEL)),
                ('purchased_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gift_cards_purchased', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GiftCardTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('issue', 'Issued'), ('claim', 'Claimed by user'), ('redeem', 'Redeemed (debit)'), ('refund', 'Refund (credit back)'), ('adjust', 'Admin adjustment'), ('expire', 'Expired (balance forfeited)'), ('cancel', 'Cancelled by admin')], db_index=True, max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ref_type', models.CharField(blank=True, db_index=True, max_length=40)),
                ('ref_id', models.CharField(blank=True, db_index=True, max_length=80)),
                ('dedupe_key', models.CharField(blank=True, db_index=True, max_length=120, null=True)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='gift_cards.giftcard')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='giftcard',
            index=models.Index(fields=['status', 'expires_at'], name='gift_cards__status_5f9b3b_idx'),
        ),
        migrations.AddIndex(
            model_name='giftcard',
            index=models.Index(fields=['claimed_by', '-created_at'], name='gift_cards__claimed_f74c92_idx'),
        ),
        migrations.AddIndex(
            model_name='giftcardtransaction',
            index=models.Index(fields=['card', '-created_at'], name='gift_cards__card_id_d41372_idx'),
        ),
        migrations.AddIndex(
            model_name='giftcardtransaction',
            index=models.Index(fields=['ref_type', 'ref_id'], name='gift_cards__ref_typ_333fb6_idx'),
        ),
        migrations.AddConstraint(
            model_name='giftcardtransaction',
            constraint=models.UniqueConstraint(fields=('card', 'dedupe_key'), name='uniq_card_dedupe_key'),
        ),
    ]
