# Generated by Django 6.0.1 on 2026-02-14 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='store',
            unique_together={('owner', 'name')},
        ),
        migrations.AddField(
            model_name='store',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='store',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='store',
            name='banner',
        ),
        migrations.RemoveField(
            model_name='store',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='store',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='store',
            name='total_reviews',
        ),
    ]
