# Generated by Django 6.0.1 on 2026-04-04 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_storereview'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='cached_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='store',
            name='total_reviews_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
