# Generated by Django 6.0.1 on 2026-04-27 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_image_hash_productgroup_and_more'),
        ('stores', '0004_store_cached_rating_store_total_reviews_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='avg_response_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='store',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='store_banners/'),
        ),
        migrations.AddField(
            model_name='store',
            name='featured_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_in_stores', to='products.product'),
        ),
        migrations.AddField(
            model_name='store',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='store',
            name='primary_color',
            field=models.CharField(default='#C9A84C', max_length=7),
        ),
    ]
