# Generated by Django 6.0.1 on 2026-05-30 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_product_free_shipping'),
        ('stores', '0005_store_avg_response_minutes_store_banner_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('ordering', models.PositiveIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('products', models.ManyToManyField(blank=True, related_name='in_collections', to='products.product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='stores.store')),
            ],
            options={
                'ordering': ['ordering', '-created_at'],
                'unique_together': {('store', 'name')},
            },
        ),
    ]
