# Generated by Django 6.0.1 on 2026-05-16 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('pattern', models.CharField(help_text='Python regex; case-insensitive when run', max_length=500)),
                ('category', models.CharField(choices=[('pii', 'PII (phone/email/IBAN)'), ('scam', 'Scam / off-platform payment'), ('phishing', 'Phishing / external links'), ('abuse', 'Abuse / harassment'), ('spam', 'Spam'), ('suspicious', 'Suspicious language (review)')], db_index=True, max_length=12)),
                ('severity', models.CharField(choices=[('info', 'Info (log only)'), ('warn', 'Warn (flag for review)'), ('hide', 'Hide content from other party'), ('block', 'Block — refuse to publish')], db_index=True, max_length=6)),
                ('applies_to', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('user_message', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'name'],
                'indexes': [models.Index(fields=['is_active', 'category'], name='content_saf_is_acti_fd36c3_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserViolationCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_24h', models.PositiveIntegerField(default=0)),
                ('window_started_at', models.DateTimeField()),
                ('last_violation_at', models.DateTimeField(blank=True, null=True)),
                ('last_severity', models.CharField(blank=True, max_length=6)),
                ('last_case_id', models.IntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='content_violations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ScanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_type', models.CharField(db_index=True, max_length=40)),
                ('ref_id', models.CharField(db_index=True, max_length=80)),
                ('severity', models.CharField(choices=[('info', 'Info (log only)'), ('warn', 'Warn (flag for review)'), ('hide', 'Hide content from other party'), ('block', 'Block — refuse to publish')], db_index=True, max_length=6)),
                ('action', models.CharField(choices=[('allow', 'Allowed'), ('flag', 'Flagged for review'), ('hide', 'Hidden from recipient'), ('block', 'Blocked')], max_length=6)),
                ('matched_rules', models.JSONField(default=list)),
                ('text_hash', models.CharField(db_index=True, max_length=64)),
                ('text_length', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['ref_type', 'ref_id'], name='content_saf_ref_typ_194b86_idx'), models.Index(fields=['actor', '-created_at'], name='content_saf_actor_i_f5d198_idx'), models.Index(fields=['severity', '-created_at'], name='content_saf_severit_301c5d_idx')],
            },
        ),
    ]
