# Generated by Django 6.0.1 on 2026-04-21 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0007_remove_rentalconfig_product_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoSalesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('province', models.CharField(blank=True, max_length=100)),
                ('order_count', models.PositiveIntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('period', models.DateField()),
            ],
            options={
                'indexes': [models.Index(fields=['period', '-total_revenue'], name='analytics_g_period_b6ac47_idx')],
                'unique_together': {('city', 'period')},
            },
        ),
        migrations.CreateModel(
            name='FunnelEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_hash', models.CharField(blank=True, db_index=True, help_text='Pseudonymous hash of user_id — not reversible', max_length=16)),
                ('session_id', models.CharField(blank=True, max_length=100)),
                ('event', models.CharField(choices=[('view', 'View'), ('add_cart', 'Add Cart'), ('checkout', 'Checkout'), ('purchase', 'Purchase')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event', '-created_at'], name='analytics_f_event_26565e_idx'), models.Index(fields=['user_hash', 'event'], name='analytics_f_user_ha_28b42b_idx')],
            },
        ),
        migrations.CreateModel(
            name='SellerPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_rate', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('avg_response_time_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('on_time_delivery_rate', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('completion_rate', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('return_rate', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('overall_score', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('tier', models.CharField(default='bronze', max_length=10)),
                ('last_calculated', models.DateTimeField(auto_now=True)),
                ('seller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='performance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['tier', '-overall_score'], name='analytics_s_tier_b8dc4b_idx')],
            },
        ),
    ]
