# Generated by Django 6.0.1 on 2026-05-24 20:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributionTouch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('utm_source', models.CharField(blank=True, default='', max_length=80)),
                ('utm_medium', models.CharField(blank=True, default='', max_length=80)),
                ('utm_campaign', models.CharField(blank=True, default='', max_length=120)),
                ('utm_content', models.CharField(blank=True, default='', max_length=120)),
                ('utm_term', models.CharField(blank=True, default='', max_length=120)),
                ('referrer', models.URLField(blank=True, default='', max_length=500)),
                ('landing_path', models.CharField(blank=True, default='', max_length=500)),
                ('occurred_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attribution_touches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analytics_attribution_touch',
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['user', '-occurred_at'], name='analytics_a_user_id_9d24ed_idx'), models.Index(fields=['session_id', '-occurred_at'], name='analytics_a_session_afecdb_idx'), models.Index(fields=['utm_source', 'utm_campaign', '-occurred_at'], name='analytics_a_utm_sou_0bcf00_idx')],
            },
        ),
    ]
