# Generated by Django 6.0.1 on 2026-05-29 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_attributiontouch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=80)),
                ('event', models.CharField(db_index=True, max_length=80)),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('path', models.CharField(blank=True, max_length=255)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('referrer', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event', '-created_at'], name='analytics_u_event_031ca3_idx'), models.Index(fields=['user', '-created_at'], name='analytics_u_user_id_2a7bc6_idx'), models.Index(fields=['session_id', '-created_at'], name='analytics_u_session_446ed8_idx')],
            },
        ),
    ]
