# Generated by Django 6.0.1 on 2026-02-14 17:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='report',
            unique_together={('reporter', 'target_type', 'target_id')},
        ),
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('actioned', 'Actioned')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='report',
            name='target_id',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='report',
            name='target_type',
            field=models.CharField(choices=[('seller', 'Seller'), ('product', 'Product')], default='seller', max_length=10),
        ),
        migrations.AlterField(
            model_name='report',
            name='reason',
            field=models.TextField(),
        ),
        migrations.RemoveField(
            model_name='report',
            name='description',
        ),
        migrations.RemoveField(
            model_name='report',
            name='is_resolved',
        ),
        migrations.RemoveField(
            model_name='report',
            name='listing_id',
        ),
        migrations.RemoveField(
            model_name='report',
            name='reported_user',
        ),
    ]
