# Generated by Django 6.0.1 on 2026-05-09 22:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceFingerprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(db_index=True, max_length=128)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('last_seen_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('use_count', models.PositiveIntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_fingerprints', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_seen_at'],
                'indexes': [models.Index(fields=['fingerprint', '-last_seen_at'], name='risk_device_fingerp_cc9862_idx')],
                'unique_together': {('fingerprint', 'user')},
            },
        ),
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_type', models.CharField(db_index=True, max_length=40)),
                ('ref_id', models.CharField(blank=True, db_index=True, max_length=80)),
                ('score', models.PositiveSmallIntegerField()),
                ('action', models.CharField(choices=[('allow', 'Allow'), ('flag', 'Flag (proceed, log)'), ('hold', 'Hold for manual review'), ('block', 'Block (refuse)')], db_index=True, max_length=10)),
                ('reasons', models.JSONField(default=list)),
                ('context', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='risk_assessments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['ref_type', 'ref_id', '-created_at'], name='risk_riskas_ref_typ_a86fd9_idx'), models.Index(fields=['user', '-created_at'], name='risk_riskas_user_id_cdcc61_idx'), models.Index(fields=['action', '-created_at'], name='risk_riskas_action_533436_idx')],
            },
        ),
    ]
