# Generated by Django 6.0.1 on 2026-02-04 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationlog',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sellerverification',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sellerverification',
            name='id_document',
            field=models.FileField(blank=True, null=True, upload_to='seller_ids/'),
        ),
        migrations.AlterField(
            model_name='sellerverification',
            name='id_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sellerverification',
            name='selfie',
            field=models.ImageField(blank=True, null=True, upload_to='seller_selfies/'),
        ),
        migrations.AlterField(
            model_name='sellerverification',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('suspended', 'Suspended'), ('expired', 'Expired')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='verificationlog',
            name='action',
            field=models.CharField(max_length=50),
        ),
    ]
