# Generated by Django 6.0.1 on 2026-04-04 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_verificationlog_note_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verificationlog',
            name='seller_verification',
        ),
        migrations.DeleteModel(
            name='SellerVerification',
        ),
        migrations.DeleteModel(
            name='VerificationLog',
        ),
    ]
