# Generated by Django 6.0.1 on 2026-04-05 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seller', '0003_remove_verificationlog_seller_verification_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SellerFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('answer', models.TextField()),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['ordering'],
            },
        ),
        migrations.CreateModel(
            name='SellerOnboardingChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_completed', models.BooleanField(default=False)),
                ('verification_submitted', models.BooleanField(default=False)),
                ('verification_approved', models.BooleanField(default=False)),
                ('first_store_created', models.BooleanField(default=False)),
                ('first_product_added', models.BooleanField(default=False)),
                ('bank_account_added', models.BooleanField(default=False)),
                ('first_sale_made', models.BooleanField(default=False)),
                ('seller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SellerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_logo', models.ImageField(blank=True, null=True, upload_to='store_logos/')),
                ('store_banner', models.ImageField(blank=True, null=True, upload_to='store_banners/')),
                ('return_policy', models.TextField(blank=True, null=True)),
                ('shipping_policy', models.TextField(blank=True, null=True)),
                ('working_hours', models.JSONField(default=dict)),
                ('is_on_holiday', models.BooleanField(default=False)),
                ('holiday_message', models.TextField(blank=True, null=True)),
                ('holiday_until', models.DateField(blank=True, null=True)),
                ('revenue_goal', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('subscription_plan', models.CharField(choices=[('free', 'Free'), ('premium', 'Premium')], default='free', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
