# Generated by Django 6.0.1 on 2026-04-30 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerannouncement',
            name='message',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='sellerfaq',
            name='answer',
            field=models.TextField(max_length=5000),
        ),
    ]
