# Generated by Django 6.0.1 on 2026-06-16 20:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerExperienceKpiSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField(unique=True)),
                ('review_submission_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('review_photo_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('subscribe_save_retention_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('loyalty_active_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('address_book_adoption_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('referral_conversion_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('active_subscriptions', models.IntegerField(default=0)),
                ('pending_bulk_inquiries', models.IntegerField(default=0)),
                ('pending_questions', models.IntegerField(default=0)),
                ('computed_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RestrictedCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('category_name', models.CharField(blank=True, max_length=120)),
                ('restriction_type', models.CharField(choices=[('alcohol', 'Alcohol'), ('tobacco', 'Tobacco'), ('adult_health', 'Adult health'), ('gambling', 'Gambling'), ('age_media', 'Age-restricted media')], default='alcohol', max_length=24)),
                ('min_age', models.PositiveSmallIntegerField(default=18)),
                ('requires_delivery_check', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AgeVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_verified', models.BooleanField(default=False)),
                ('method', models.CharField(choices=[('self_declaration', 'Self-declaration'), ('kyc_dob', 'KYC date of birth')], default='self_declaration', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('buyer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='age_verification', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BulkInquiry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_id', models.CharField(db_index=True, max_length=64)),
                ('sku_id', models.CharField(blank=True, max_length=64)),
                ('quantity', models.PositiveIntegerField()),
                ('delivery_province', models.CharField(blank=True, max_length=40)),
                ('required_by_date', models.DateField(blank=True, null=True)),
                ('purpose', models.CharField(choices=[('resale', 'Resale'), ('personal', 'Personal'), ('business', 'Business'), ('institution', 'Institution'), ('other', 'Other')], default='resale', max_length=12)),
                ('buyer_message', models.TextField(blank=True)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('nif', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('viewed', 'Viewed'), ('quoted', 'Quoted'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired')], db_index=True, default='submitted', max_length=10)),
                ('seller_quote_cents', models.IntegerField(blank=True, null=True)),
                ('seller_message', models.TextField(blank=True)),
                ('order_id', models.CharField(blank=True, max_length=64)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_inquiries', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_bulk_inquiries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BuyerExperienceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(db_index=True, max_length=48)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyer_exp_events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderGiftOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('is_gift', models.BooleanField(default=False)),
                ('gift_message', models.CharField(blank=True, max_length=300)),
                ('hide_price', models.BooleanField(default=True)),
                ('gift_wrap', models.CharField(choices=[('none', 'Not wrapped'), ('basic', 'Basic wrap'), ('premium', 'Premium wrap')], default='none', max_length=8)),
                ('gift_wrap_fee_cents', models.IntegerField(default=0)),
                ('gift_receipt_key', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gift_orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PrePurchaseQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_id', models.CharField(db_index=True, max_length=64)),
                ('question_text', models.TextField()),
                ('attachment_key', models.CharField(blank=True, max_length=300)),
                ('answer_text', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('answered', 'Answered'), ('held', 'Held (moderation)'), ('expired', 'Expired')], db_index=True, default='pending', max_length=10)),
                ('moderation_flag', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asked_questions', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pre_purchase_questions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(db_index=True, max_length=64)),
                ('sku_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('price_cents', models.BigIntegerField()),
                ('currency', models.CharField(default='AOA', max_length=3)),
                ('change_reason', models.CharField(choices=[('seller_update', 'Seller update'), ('promotion', 'Promotion'), ('flash_sale', 'Flash sale'), ('system_auto', 'System auto'), ('admin_override', 'Admin override')], default='seller_update', max_length=16)),
                ('recorded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'indexes': [models.Index(fields=['product_id', '-recorded_at'], name='buyer_exper_product_f7fe58_idx')],
            },
        ),
        migrations.CreateModel(
            name='SavedComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120)),
                ('product_ids', models.JSONField(default=list)),
                ('share_code', models.CharField(blank=True, db_index=True, max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_comparisons', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_id', models.CharField(db_index=True, max_length=64)),
                ('sku_id', models.CharField(blank=True, max_length=64)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('frequency_days', models.PositiveIntegerField(default=30)),
                ('discount_pct', models.DecimalField(decimal_places=2, default=8, max_digits=5)),
                ('next_order_date', models.DateField(db_index=True)),
                ('payment_method', models.CharField(default='wallet', max_length=24)),
                ('delivery_address_id', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('cancelled', 'Cancelled')], db_index=True, default='active', max_length=10)),
                ('total_orders', models.PositiveIntegerField(default=0)),
                ('total_spent_cents', models.BigIntegerField(default=0)),
                ('consecutive_failures', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'next_order_date'], name='buyer_exper_status_751953_idx')],
            },
        ),
        migrations.CreateModel(
            name='WishlistPriceWatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(db_index=True, max_length=64)),
                ('sku_id', models.CharField(blank=True, max_length=64)),
                ('price_at_add_cents', models.BigIntegerField()),
                ('threshold_pct', models.DecimalField(decimal_places=2, default=5, max_digits=5)),
                ('alert_enabled', models.BooleanField(default=True)),
                ('last_alerted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_watches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('buyer', 'product_id', 'sku_id')},
            },
        ),
    ]
