# Generated by Django 6.0.1 on 2026-04-14 14:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductEmbedding',
            fields=[
                ('product_id', models.UUIDField(primary_key=True, serialize=False)),
                ('embedding', models.JSONField(default=list)),
                ('category', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tags', models.JSONField(default=list)),
                ('popularity_score', models.FloatField(default=0.0)),
                ('computed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ai_product_embeddings',
            },
        ),
        migrations.CreateModel(
            name='SimilarProductsCache',
            fields=[
                ('product_id', models.UUIDField(primary_key=True, serialize=False)),
                ('similar_product_ids', models.JSONField(default=list)),
                ('similarity_scores', models.JSONField(default=list)),
                ('computed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ai_similar_products_cache',
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('push_enabled', models.BooleanField(default=True)),
                ('email_enabled', models.BooleanField(default=True)),
                ('sms_enabled', models.BooleanField(default=False)),
                ('price_drops', models.BooleanField(default=True)),
                ('flash_sales', models.BooleanField(default=True)),
                ('new_recommendations', models.BooleanField(default=True)),
                ('order_updates', models.BooleanField(default=True)),
                ('chat_messages', models.BooleanField(default=True)),
                ('quiet_hours_start', models.TimeField(blank=True, null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, null=True)),
                ('max_daily_recommendations', models.PositiveSmallIntegerField(default=3)),
                ('max_daily_flash_sales', models.PositiveSmallIntegerField(default=2)),
                ('last_notified_at', models.DateTimeField(blank=True, null=True)),
                ('daily_notification_count', models.PositiveSmallIntegerField(default=0)),
                ('notification_count_reset_at', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_notification_preferences',
            },
        ),
        migrations.CreateModel(
            name='SizeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height_cm', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('weight_kg', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('chest_cm', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('waist_cm', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('hips_cm', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('clothing_size', models.CharField(blank=True, choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=5)),
                ('shoe_size_eu', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('inferred_sizes', models.JSONField(default=dict)),
                ('fit_preference', models.CharField(blank=True, choices=[('slim', 'Slim fit'), ('regular', 'Regular fit'), ('loose', 'Loose fit')], max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_size_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_size_profiles',
            },
        ),
        migrations.CreateModel(
            name='UserTasteProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('preferred_categories', models.JSONField(default=list)),
                ('budget_min', models.PositiveIntegerField(default=0)),
                ('budget_max', models.PositiveIntegerField(default=999999)),
                ('shopping_for', models.CharField(choices=[('self', 'Self'), ('others', 'Others'), ('both', 'Both')], default='self', max_length=20)),
                ('province', models.CharField(default='Luanda', max_length=50)),
                ('style_tags', models.JSONField(default=list)),
                ('category_scores', models.JSONField(default=dict)),
                ('brand_scores', models.JSONField(default=dict)),
                ('avg_purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('price_sensitivity', models.FloatField(default=0.5)),
                ('embedding', models.JSONField(blank=True, null=True)),
                ('embedding_updated_at', models.DateTimeField(blank=True, null=True)),
                ('total_views', models.PositiveIntegerField(default=0)),
                ('total_purchases', models.PositiveIntegerField(default=0)),
                ('total_wishlist_adds', models.PositiveIntegerField(default=0)),
                ('avg_session_duration', models.FloatField(default=0)),
                ('quiz_completed', models.BooleanField(default=False)),
                ('quiz_completed_at', models.DateTimeField(blank=True, null=True)),
                ('profile_confidence', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_taste_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_user_taste_profiles',
            },
        ),
        migrations.CreateModel(
            name='BehavioralEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('view', 'Product view'), ('dwell', 'Long dwell (>30s)'), ('wishlist_add', 'Added to wishlist'), ('wishlist_remove', 'Removed from wishlist'), ('cart_add', 'Added to cart'), ('cart_remove', 'Removed from cart'), ('purchase', 'Purchased'), ('return', 'Returned product'), ('search', 'Search query'), ('click', 'Recommendation click'), ('share', 'Shared product'), ('review', 'Left a review'), ('chat_start', 'Started chat with seller')], max_length=20)),
                ('product_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('session_id', models.CharField(blank=True, max_length=100)),
                ('source', models.CharField(blank=True, max_length=30)),
                ('dwell_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('signal_weight', models.FloatField(default=1.0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_behavioral_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_behavioral_events',
                'indexes': [models.Index(fields=['user', 'created_at'], name='ai_behavior_user_id_30c3aa_idx'), models.Index(fields=['user', 'event_type'], name='ai_behavior_user_id_5bbc78_idx'), models.Index(fields=['product_id', 'event_type'], name='ai_behavior_product_0dff38_idx')],
            },
        ),
        migrations.CreateModel(
            name='PriceDropAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_id', models.UUIDField(db_index=True)),
                ('price_when_added', models.DecimalField(decimal_places=2, max_digits=12)),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('alert_threshold_pct', models.FloatField(default=10.0)),
                ('status', models.CharField(choices=[('watching', 'Watching'), ('triggered', 'Alert sent'), ('dismissed', 'Dismissed')], default='watching', max_length=20)),
                ('triggered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_price_drop_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_price_drop_alerts',
                'unique_together': {('user', 'product_id')},
            },
        ),
        migrations.CreateModel(
            name='RecommendationCache',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feed_type', models.CharField(choices=[('home_feed', 'Personalised home feed'), ('similar', 'Similar products'), ('trending', 'Trending for you'), ('flash_targets', 'Flash sale targets'), ('cross_sell', 'Cross-sell suggestions')], max_length=20)),
                ('context_id', models.UUIDField(blank=True, null=True)),
                ('product_ids', models.JSONField(default=list)),
                ('scores', models.JSONField(default=list)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField()),
                ('is_cold_start', models.BooleanField(default=False)),
                ('algorithm_version', models.CharField(default='v1', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_recommendation_caches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_recommendation_caches',
                'indexes': [models.Index(fields=['user', 'feed_type'], name='ai_recommen_user_id_9c5a6d_idx')],
                'unique_together': {('user', 'feed_type', 'context_id')},
            },
        ),
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('raw_query', models.CharField(max_length=500)),
                ('normalized_query', models.CharField(blank=True, max_length=500)),
                ('detected_category', models.CharField(blank=True, max_length=50)),
                ('detected_price_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('detected_price_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('detected_occasion', models.CharField(blank=True, max_length=100)),
                ('detected_style', models.CharField(blank=True, max_length=100)),
                ('detected_language', models.CharField(default='pt', max_length=10)),
                ('results_count', models.PositiveIntegerField(default=0)),
                ('clicked_result_id', models.UUIDField(blank=True, null=True)),
                ('session_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_search_queries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_search_queries',
                'indexes': [models.Index(fields=['user', 'created_at'], name='ai_search_q_user_id_7c6e97_idx'), models.Index(fields=['normalized_query'], name='ai_search_q_normali_c0aa12_idx')],
            },
        ),
    ]
