# Generated by Django 6.0.1 on 2026-04-14 15:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ABTestAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experiment_name', models.CharField(max_length=100)),
                ('variant', models.CharField(max_length=50)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('converted', models.BooleanField(default=False)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ai_ab_test_assignments',
            },
        ),
        migrations.CreateModel(
            name='AIConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_id', models.UUIDField(blank=True, null=True)),
                ('product_name', models.CharField(blank=True, max_length=255)),
                ('messages', models.JSONField(default=list, help_text='[{role: user|assistant, content: str}, ...]')),
                ('total_tokens_used', models.PositiveIntegerField(default=0)),
                ('total_cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=8)),
                ('led_to_purchase', models.BooleanField(default=False)),
                ('led_to_cart_add', models.BooleanField(default=False)),
                ('user_rating', models.PositiveSmallIntegerField(blank=True, help_text='1-5 stars from user feedback on AI response', null=True)),
                ('language', models.CharField(default='pt', max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ai_conversations',
            },
        ),
        migrations.RemoveIndex(
            model_name='behavioralevent',
            name='ai_behavior_user_id_30c3aa_idx',
        ),
        migrations.RemoveIndex(
            model_name='searchquery',
            name='ai_search_q_user_id_7c6e97_idx',
        ),
        migrations.RemoveIndex(
            model_name='searchquery',
            name='ai_search_q_normali_c0aa12_idx',
        ),
        migrations.RenameField(
            model_name='usertasteprofile',
            old_name='avg_session_duration',
            new_name='avg_session_duration_seconds',
        ),
        migrations.RemoveField(
            model_name='notificationpreference',
            name='last_notified_at',
        ),
        migrations.RemoveField(
            model_name='notificationpreference',
            name='sms_enabled',
        ),
        migrations.AddField(
            model_name='behavioralevent',
            name='converted',
            field=models.BooleanField(help_text='True if event led to purchase in same session', null=True),
        ),
        migrations.AddField(
            model_name='behavioralevent',
            name='scroll_depth_pct',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='behavioralevent',
            name='seller_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='behavioralevent',
            name='subcategory',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='pricedropalert',
            name='lowest_seen_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='pricedropalert',
            name='product_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='pricedropalert',
            name='times_triggered',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productembedding',
            name='avg_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='productembedding',
            name='embedding_model',
            field=models.CharField(default='text-embedding-3-small', max_length=50),
        ),
        migrations.AddField(
            model_name='productembedding',
            name='embedding_text',
            field=models.TextField(blank=True, help_text='Input text that was embedded'),
        ),
        migrations.AddField(
            model_name='productembedding',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productembedding',
            name='is_express',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productembedding',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='productembedding',
            name='province',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='productembedding',
            name='seller_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='productembedding',
            name='subcategory',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='productembedding',
            name='total_sales',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productembedding',
            name='total_views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recommendationcache',
            name='ctr',
            field=models.FloatField(default=0.0, help_text='Click-through rate — measured after serving'),
        ),
        migrations.AddField(
            model_name='recommendationcache',
            name='cvr',
            field=models.FloatField(default=0.0, help_text='Conversion rate'),
        ),
        migrations.AddField(
            model_name='recommendationcache',
            name='score_breakdown',
            field=models.JSONField(default=dict, help_text='Per-product score breakdown for debugging: {product_id: {category: 0.4, price: 0.3, ...}}'),
        ),
        migrations.AddField(
            model_name='searchquery',
            name='clicked_product_ids',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='searchquery',
            name='parsed_intent',
            field=models.JSONField(default=dict, help_text='Full GPT parsed output: {category, price_max, occasion, style, keywords}'),
        ),
        migrations.AddField(
            model_name='searchquery',
            name='purchased_after_search',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='searchquery',
            name='zero_results',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='similarproductscache',
            name='algorithm',
            field=models.CharField(default='cosine_openai', max_length=20),
        ),
        migrations.AddField(
            model_name='sizeprofile',
            name='return_reasons',
            field=models.JSONField(default=list, help_text='[{product_id, reason: too_small|too_large|wrong_fit, date}]'),
        ),
        migrations.AddField(
            model_name='usertasteprofile',
            name='active_algorithm',
            field=models.CharField(choices=[('cold_start', 'Cold start — popularity-based'), ('quiz_seeded', 'Quiz seeded — category boosted'), ('behavioral', 'Behavioral — full ML'), ('hybrid', 'Hybrid — ML + popularity blend')], default='cold_start', max_length=20),
        ),
        migrations.AddField(
            model_name='usertasteprofile',
            name='country',
            field=models.CharField(choices=[('AO', 'Angola'), ('ZW', 'Zimbabwe'), ('ZM', 'Zambia'), ('BW', 'Botswana'), ('NA', 'Namibia'), ('ZA', 'South Africa'), ('MZ', 'Mozambique'), ('TZ', 'Tanzania'), ('MW', 'Malawi'), ('LS', 'Lesotho')], default='AO', max_length=2),
        ),
        migrations.AddField(
            model_name='usertasteprofile',
            name='days_since_last_active',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usertasteprofile',
            name='embedding_model',
            field=models.CharField(default='text-embedding-3-small', max_length=50),
        ),
        migrations.AddField(
            model_name='usertasteprofile',
            name='embedding_text',
            field=models.TextField(blank=True, help_text='The text that was embedded — for debugging and re-embedding'),
        ),
        migrations.AddField(
            model_name='usertasteprofile',
            name='preferred_language',
            field=models.CharField(choices=[('pt', 'Portuguese'), ('en', 'English')], default='pt', max_length=5),
        ),
        migrations.AddField(
            model_name='usertasteprofile',
            name='purchasing_power_index',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='usertasteprofile',
            name='seller_affinity',
            field=models.JSONField(default=dict, help_text="{'seller_id': score} — users tend to rebuy from same sellers"),
        ),
        migrations.AddField(
            model_name='usertasteprofile',
            name='total_chat_starts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usertasteprofile',
            name='total_searches',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='behavioralevent',
            name='category',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='behavioralevent',
            name='event_type',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='behavioralevent',
            name='session_id',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='behavioralevent',
            name='source',
            field=models.CharField(blank=True, choices=[('home_feed', 'Home feed'), ('search', 'Search results'), ('recommendation', 'AI recommendation'), ('similar', 'Similar products'), ('direct', 'Direct navigation'), ('notification', 'Push notification'), ('flash_sale', 'Flash sale'), ('share', 'Shared link')], max_length=30),
        ),
        migrations.AlterField(
            model_name='productembedding',
            name='category',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='recommendationcache',
            name='algorithm_version',
            field=models.CharField(default='v2', max_length=20),
        ),
        migrations.AlterField(
            model_name='recommendationcache',
            name='feed_type',
            field=models.CharField(choices=[('home_feed', 'Home feed'), ('similar', 'Similar products'), ('trending', 'Trending for you'), ('flash_target', 'Flash sale target'), ('cross_sell', 'Cross-sell'), ('recently_viewed_similar', 'Based on recently viewed')], max_length=30),
        ),
        migrations.AlterField(
            model_name='searchquery',
            name='detected_category',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='searchquery',
            name='detected_language',
            field=models.CharField(default='pt', max_length=5),
        ),
        migrations.AlterField(
            model_name='searchquery',
            name='raw_query',
            field=models.CharField(db_index=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='usertasteprofile',
            name='budget_max',
            field=models.PositiveIntegerField(default=999999, help_text='Kz'),
        ),
        migrations.AlterField(
            model_name='usertasteprofile',
            name='budget_min',
            field=models.PositiveIntegerField(default=0, help_text='Kz'),
        ),
        migrations.AlterField(
            model_name='usertasteprofile',
            name='category_scores',
            field=models.JSONField(default=dict, help_text="{'Moda': 0.85, 'Tech': 0.2} — learned from behavior"),
        ),
        migrations.AlterField(
            model_name='usertasteprofile',
            name='price_sensitivity',
            field=models.FloatField(default=0.5, help_text='0=insensitive, 1=very price sensitive. Learned from browse vs purchase gap.'),
        ),
        migrations.AlterField(
            model_name='usertasteprofile',
            name='profile_confidence',
            field=models.FloatField(default=0.0, help_text='0=cold start, 1=fully warmed up. Determines algorithm choice.'),
        ),
        migrations.AlterField(
            model_name='usertasteprofile',
            name='province',
            field=models.CharField(choices=[('Luanda', 'Luanda'), ('Benguela', 'Benguela'), ('Huambo', 'Huambo'), ('Huíla', 'Huíla'), ('Cabinda', 'Cabinda'), ('Uíge', 'Uíge'), ('Namibe', 'Namibe'), ('Malanje', 'Malanje'), ('Bié', 'Bié'), ('Moxico', 'Moxico'), ('Cunene', 'Cunene'), ('Cuando Cubango', 'Cuando Cubango'), ('Lunda Norte', 'Lunda Norte'), ('Lunda Sul', 'Lunda Sul'), ('Kwanza Norte', 'Kwanza Norte'), ('Kwanza Sul', 'Kwanza Sul'), ('Bengo', 'Bengo'), ('Zaire', 'Zaire')], default='Luanda', max_length=50),
        ),
        migrations.AlterField(
            model_name='usertasteprofile',
            name='shopping_for',
            field=models.CharField(choices=[('self', 'Self'), ('family', 'Family'), ('business', 'Business'), ('gifts', 'Gifts')], default='self', max_length=20),
        ),
        migrations.AddIndex(
            model_name='behavioralevent',
            index=models.Index(fields=['user', '-created_at'], name='ai_behavior_user_id_efc791_idx'),
        ),
        migrations.AddIndex(
            model_name='behavioralevent',
            index=models.Index(fields=['session_id'], name='ai_behavior_session_896d38_idx'),
        ),
        migrations.AddIndex(
            model_name='behavioralevent',
            index=models.Index(fields=['category', 'event_type'], name='ai_behavior_categor_2b1278_idx'),
        ),
        migrations.AddIndex(
            model_name='behavioralevent',
            index=models.Index(fields=['-created_at'], name='ai_behavior_created_e07d0f_idx'),
        ),
        migrations.AddIndex(
            model_name='pricedropalert',
            index=models.Index(fields=['status', 'product_id'], name='ai_price_dr_status_3b1b09_idx'),
        ),
        migrations.AddIndex(
            model_name='productembedding',
            index=models.Index(fields=['category', 'is_active'], name='ai_product__categor_d67ada_idx'),
        ),
        migrations.AddIndex(
            model_name='productembedding',
            index=models.Index(fields=['-popularity_score'], name='ai_product__popular_4df92d_idx'),
        ),
        migrations.AddIndex(
            model_name='productembedding',
            index=models.Index(fields=['price'], name='ai_product__price_15dcbb_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendationcache',
            index=models.Index(fields=['expires_at'], name='ai_recommen_expires_106baf_idx'),
        ),
        migrations.AddIndex(
            model_name='searchquery',
            index=models.Index(fields=['user', '-created_at'], name='ai_search_q_user_id_9fc6b9_idx'),
        ),
        migrations.AddIndex(
            model_name='searchquery',
            index=models.Index(fields=['detected_category'], name='ai_search_q_detecte_0b5c29_idx'),
        ),
        migrations.AddIndex(
            model_name='searchquery',
            index=models.Index(fields=['zero_results'], name='ai_search_q_zero_re_489797_idx'),
        ),
        migrations.AddIndex(
            model_name='usertasteprofile',
            index=models.Index(fields=['country', 'province'], name='ai_user_tas_country_f55823_idx'),
        ),
        migrations.AddIndex(
            model_name='usertasteprofile',
            index=models.Index(fields=['active_algorithm'], name='ai_user_tas_active__623fa0_idx'),
        ),
        migrations.AddIndex(
            model_name='usertasteprofile',
            index=models.Index(fields=['profile_confidence'], name='ai_user_tas_profile_c4f241_idx'),
        ),
        migrations.AddField(
            model_name='abtestassignment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_ab_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aiconversation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='searchquery',
            name='clicked_result_id',
        ),
        migrations.AlterUniqueTogether(
            name='abtestassignment',
            unique_together={('user', 'experiment_name')},
        ),
        migrations.AddIndex(
            model_name='aiconversation',
            index=models.Index(fields=['user', '-created_at'], name='ai_conversa_user_id_7542e0_idx'),
        ),
        migrations.AddIndex(
            model_name='aiconversation',
            index=models.Index(fields=['product_id'], name='ai_conversa_product_aa6e4e_idx'),
        ),
    ]
