# Generated by Django 6.0.1 on 2026-05-15 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InboundWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(db_index=True, max_length=40)),
                ('body_sha256', models.CharField(db_index=True, max_length=64)),
                ('body_excerpt', models.TextField(blank=True)),
                ('signature_header', models.CharField(blank=True, max_length=500)),
                ('timestamp_header', models.CharField(blank=True, max_length=64)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('received', 'Received (in-flight)'), ('signature_invalid', 'Rejected — bad signature'), ('missing_signature', 'Rejected — no signature header'), ('replay_detected', 'Rejected — duplicate body'), ('stale_timestamp', 'Rejected — timestamp outside window'), ('malformed', 'Rejected — body unparseable'), ('processed', 'Verified + handler succeeded'), ('handler_failed', 'Verified but handler raised')], db_index=True, default='received', max_length=20)),
                ('event_type', models.CharField(blank=True, db_index=True, max_length=80)),
                ('response_status', models.PositiveSmallIntegerField(default=200)),
                ('response_body', models.TextField(blank=True)),
                ('error', models.TextField(blank=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['provider', '-received_at'], name='inbound_web_provide_28a5b3_idx'), models.Index(fields=['status', '-received_at'], name='inbound_web_status_9ad83f_idx')],
                'constraints': [models.UniqueConstraint(fields=('provider', 'body_sha256'), name='uniq_provider_body_hash')],
            },
        ),
    ]
