# Generated by Django 6.0.1 on 2026-05-23 00:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_suppression_and_log'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BroadcastNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('segment', models.CharField(choices=[('all_buyers', 'Todos os compradores'), ('all_sellers', 'Todos os vendedores'), ('province', 'Província específica'), ('category_interest', 'Interesse de categoria'), ('inactive_30', 'Inactivos há 30+ dias'), ('new_users', 'Novos utilizadores (últimos 7 dias)'), ('custom', 'Lista personalizada')], max_length=30)),
                ('segment_value', models.CharField(blank=True, help_text='Province name, category name, etc.', max_length=100)),
                ('channel', models.CharField(choices=[('push', 'Push notification'), ('inapp', 'In-app notification'), ('both', 'Push + In-app')], default='both', max_length=10)),
                ('deep_link', models.CharField(blank=True, help_text='App screen to open e.g. /explore?category=Moda', max_length=200)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('recipient_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('scheduled', 'Agendado'), ('sent', 'Enviado'), ('failed', 'Falhou')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'broadcast_notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='notificationlog',
            new_name='notificatio_user_id_57d53d_idx',
            old_name='notifs_log_user_idx',
        ),
        migrations.RenameIndex(
            model_name='notificationlog',
            new_name='notificatio_email_0a7d65_idx',
            old_name='notifs_log_email_idx',
        ),
        migrations.RenameIndex(
            model_name='notificationlog',
            new_name='notificatio_categor_15d528_idx',
            old_name='notifs_log_cat_idx',
        ),
        migrations.RenameIndex(
            model_name='suppressedemail',
            new_name='notificatio_reason_68bb80_idx',
            old_name='notifs_supp_reason_idx',
        ),
        migrations.AddField(
            model_name='broadcastnotification',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
