# Generated by Django 6.0.1 on 2026-05-24 00:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_broadcastnotification_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(unique=True)),
                ('platform', models.CharField(choices=[('ios', 'iOS (APNs via FCM)'), ('android', 'Android (FCM)'), ('web', 'Web push')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('deactivation_reason', models.CharField(blank=True, choices=[('logout', 'User logged out'), ('fcm_invalid', 'FCM rejected as invalid'), ('fcm_unregistered', 'FCM reported app uninstalled'), ('replaced', 'Replaced by newer registration'), ('admin', 'Admin / ops action')], default='', max_length=20)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_info', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications_device_token',
                'indexes': [models.Index(fields=['user', 'is_active'], name='notificatio_user_id_b514bd_idx')],
            },
        ),
    ]
