# Generated by Django 6.0.1 on 2026-05-24 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_devicetoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('order', 'Order Update'), ('payment', 'Payment'), ('message', 'Message'), ('review', 'Review'), ('promotion', 'Promotion'), ('system', 'System'), ('verification', 'Verification'), ('dispute', 'Dispute'), ('cart_abandonment', 'Cart Abandonment Reminder')], max_length=20),
        ),
    ]
